// Generated by cdef_gen from the HilComparator spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_COMPARATOR_TUNABLE_PARAMS_HPP
#define APEX_CDEF_AUTO_COMPARATOR_TUNABLE_PARAMS_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace support {

/// Spec-defined tunable parameters (8 bytes, packed by
/// construction: field order and sizes come from the spec).
struct ComparatorTunableParams {
  float warnThreshold{0.1F}; ///< Divergence magnitude warning threshold [N].
  float reserved{0.0F}; ///< Reserved for alignment.
};
static_assert(sizeof(ComparatorTunableParams) == 8, "layout diverged from the spec");
static_assert(offsetof(ComparatorTunableParams, warnThreshold) == 0, "field offset diverged");
static_assert(offsetof(ComparatorTunableParams, reserved) == 4, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t COMPARATOR_TUNABLE_PARAMS_LAYOUT_HASH = 0x37BF5D88U;

} // namespace support
} // namespace appsim
#endif // APEX_CDEF_AUTO_COMPARATOR_TUNABLE_PARAMS_HPP
