// Generated by cdef_gen from the HilComparator spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_COMPARATOR_STATE_HPP
#define APEX_CDEF_AUTO_COMPARATOR_STATE_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace support {

/// Spec-defined tunable parameters (16 bytes, packed by
/// construction: field order and sizes come from the spec).
struct ComparatorState {
  float maxDivergence{}; ///< Maximum observed divergence [N].
  std::uint32_t compareCount{}; ///< Total comparisons executed.
  std::uint32_t warnCount{}; ///< Threshold warnings issued.
  std::uint32_t reserved{}; ///< Reserved for alignment.
};
static_assert(sizeof(ComparatorState) == 16, "layout diverged from the spec");
static_assert(offsetof(ComparatorState, maxDivergence) == 0, "field offset diverged");
static_assert(offsetof(ComparatorState, compareCount) == 4, "field offset diverged");
static_assert(offsetof(ComparatorState, warnCount) == 8, "field offset diverged");
static_assert(offsetof(ComparatorState, reserved) == 12, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t COMPARATOR_STATE_LAYOUT_HASH = 0x16E14D96U;

} // namespace support
} // namespace appsim
#endif // APEX_CDEF_AUTO_COMPARATOR_STATE_HPP
