/**
 * @file 00_HorizonProceduralHtile_dTest.cpp
 * @brief Integration test: load a horizon-CLI-generated .htile through
 *        Apex's HtileTile consumer.
 *
 * Goals:
 *  - Verify the horizon procedural terrain pipeline emits an apex-readable
 *    htile (wire-format compatibility check, parallel to the gravity dtest
 *    in 01_HorizonProceduralGravity_dTest.cpp).
 *  - Validate elevation queries on a global (-90..90, -180..180) tile.
 *
 * Prereqs:
 *  - alpha_global_lod1.htile in data/procedural/, generated by:
 *      horizon_world gen-terrain --spec alpha.toml \
 *          --out alpha_global_lod1.htile \
 *          --lat-min -90 --lat-max 90 --lon-min -180 --lon-max 180 \
 *          --dim-lat 512 --dim-lon 1024 --lod 1
 *
 * Notes:
 *  - SKIPs cleanly if the fixture is absent.
 *  - Run manually:
 *      ./build/native-linux-debug/bin/devtests/SimEnvironmentTerrain_Dev \
 *          --gtest_filter="HorizonProceduralHtile*"
 */

#include "src/sim/environment/terrain/inc/Htile.hpp"
#include "src/sim/environment/terrain/inc/HtileTile.hpp"
#include "src/sim/environment/terrain/inc/TerrainStatus.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <iomanip>
#include <iostream>

using sim::environment::terrain::HtileTile;
using sim::environment::terrain::isSuccess;
using sim::environment::terrain::Status;

namespace {

constexpr const char* K_ALPHA_TILE_PATH =
    "src/sim/environment/terrain/data/procedural/alpha_global_lod1.htile";

constexpr double K_DEG_PER_RAD = 57.295779513082320876798154814105;

} // namespace

TEST(HorizonProceduralHtile, TileLoadsAndHeaderMatches) {
  std::cout << "\n=== Horizon procedural htile: load + header ===\n";

  HtileTile t;
  if (!isSuccess(t.load(K_ALPHA_TILE_PATH))) {
    GTEST_SKIP() << "procedural fixture not present: " << K_ALPHA_TILE_PATH;
  }

  std::cout << "  body         : " << std::string(t.header().body, 16).c_str() << "\n";
  std::cout << "  ref_surface  : " << std::string(t.header().ref_surface, 16).c_str() << "\n";
  std::cout << "  ref_radius_m : " << t.header().ref_radius_m << "\n";
  std::cout << "  dims         : " << t.header().dim_lat << " x " << t.header().dim_lon << "\n";
  std::cout << "  lod          : " << t.header().lod << "\n";
  std::cout << "  resolution_m : " << t.resolutionMeters() << "\n";

  EXPECT_STREQ(t.header().body, "alpha");
  EXPECT_STREQ(t.header().ref_surface, "sphere");
  EXPECT_DOUBLE_EQ(t.header().ref_radius_m, 6.0e6);
  EXPECT_EQ(t.header().dim_lat, 512u);
  EXPECT_EQ(t.header().dim_lon, 1024u);
  EXPECT_EQ(t.header().lod, 1u);
  EXPECT_GT(t.resolutionMeters(), 0.0);
}

TEST(HorizonProceduralHtile, ElevationsAreSane) {
  HtileTile t;
  if (!isSuccess(t.load(K_ALPHA_TILE_PATH))) {
    GTEST_SKIP() << "procedural fixture not present";
  }

  // Sample a 5x5 grid across the body. Every query should succeed (no
  // voids in procedural data) and return a height within the body's
  // configured elev bounds (alpha sample uses [-5000, 5000] m).
  std::cout << "\n=== Horizon procedural htile: elevation sample grid ===\n";
  std::cout << std::fixed << std::setprecision(1);
  int success = 0;
  double minH = 1e9;
  double maxH = -1e9;
  for (int li = -2; li <= 2; ++li) {
    for (int lj = -2; lj <= 2; ++lj) {
      const double LAT = (60.0 * li) / K_DEG_PER_RAD; // -120..120 deg, clamped
      const double LON = (90.0 * lj) / K_DEG_PER_RAD;
      double H = 0.0;
      // Skip out-of-bounds picks (lat outside [-90, 90]).
      if (std::abs(LAT) > 89.0 / K_DEG_PER_RAD)
        continue;
      if (!isSuccess(t.elevationAt(LAT, LON, H)))
        continue;
      EXPECT_TRUE(std::isfinite(H));
      EXPECT_GE(H, -5500.0); // some slack on bounds
      EXPECT_LE(H, 5500.0);
      ++success;
      if (H < minH)
        minH = H;
      if (H > maxH)
        maxH = H;
    }
  }
  std::cout << "  successful queries: " << success << "\n";
  std::cout << "  observed range: [" << minH << ", " << maxH << "] m\n";
  EXPECT_GT(success, 0);
}

TEST(HorizonProceduralHtile, EquatorRayMatchesEcef) {
  HtileTile t;
  if (!isSuccess(t.load(K_ALPHA_TILE_PATH))) {
    GTEST_SKIP() << "procedural fixture not present";
  }

  // Pick an equatorial point; build the ECEF for it; verify both query
  // forms agree.
  const double LAT = 0.0;
  const double LON = 30.0 / K_DEG_PER_RAD;
  const double R = t.header().ref_radius_m;
  const double EC[3] = {R * std::cos(LAT) * std::cos(LON), R * std::cos(LAT) * std::sin(LON),
                        R * std::sin(LAT)};
  double H_GEO = 0.0;
  double H_ECEF = 0.0;
  ASSERT_EQ(t.elevationAt(LAT, LON, H_GEO), Status::SUCCESS);
  ASSERT_EQ(t.elevationAtEcef(EC, H_ECEF), Status::SUCCESS);
  EXPECT_NEAR(H_GEO, H_ECEF, 1e-6);
}
