// Generated by cdef_gen from the SpecActuator spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_POSITION_RESPONSE_HPP
#define APEX_CDEF_AUTO_POSITION_RESPONSE_HPP

#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (8 bytes, packed by
/// construction: field order and sizes come from the spec).
struct PositionResponse {
  float position{}; ///< Current position [units].
  std::uint8_t moving{}; ///< 1 while outside the hold band, 0 when settled.
  std::uint8_t reserved[3]{};
};
static_assert(sizeof(PositionResponse) == 8, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t POSITION_RESPONSE_LAYOUT_HASH = 0x2F8EB15EU;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_POSITION_RESPONSE_HPP
