// Generated by cdef_gen from the SpecActuator spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_ACTUATOR_OUTPUT_HPP
#define APEX_CDEF_AUTO_SPEC_ACTUATOR_OUTPUT_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (8 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecActuatorOutput {
  float position{}; ///< Published position [units].
  std::uint32_t sequence{}; ///< Monotonic publish counter.
};
static_assert(sizeof(SpecActuatorOutput) == 8, "layout diverged from the spec");
static_assert(offsetof(SpecActuatorOutput, position) == 0, "field offset diverged");
static_assert(offsetof(SpecActuatorOutput, sequence) == 4, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_ACTUATOR_OUTPUT_LAYOUT_HASH = 0x0ED217B1U;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_ACTUATOR_OUTPUT_HPP
