// Generated by cdef_gen from the SpecActuator spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_ACTUATOR_STATE_HPP
#define APEX_CDEF_AUTO_SPEC_ACTUATOR_STATE_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (16 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecActuatorState {
  float position{}; ///< Current position [units].
  float target{}; ///< Commanded target [units].
  std::uint32_t moves{}; ///< Accepted move commands.
  std::uint32_t rejects{}; ///< Rejected move commands (out-of-range target).
};
static_assert(sizeof(SpecActuatorState) == 16, "layout diverged from the spec");
static_assert(offsetof(SpecActuatorState, position) == 0, "field offset diverged");
static_assert(offsetof(SpecActuatorState, target) == 4, "field offset diverged");
static_assert(offsetof(SpecActuatorState, moves) == 8, "field offset diverged");
static_assert(offsetof(SpecActuatorState, rejects) == 12, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_ACTUATOR_STATE_LAYOUT_HASH = 0xA59DE7BBU;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_ACTUATOR_STATE_HPP
