// Generated by cdef_gen from the SpecActuator spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_ACTUATOR_TUNABLE_PARAMS_HPP
#define APEX_CDEF_AUTO_SPEC_ACTUATOR_TUNABLE_PARAMS_HPP

#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (12 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecActuatorTunableParams {
  float rateLimit{5.0F}; ///< Slew rate limit [units/s], range 0.1..50.
  float holdBand{0.1F}; ///< Hold band around the target: inside it the actuator is settled.
  float startPosition{0.0F}; ///< Position adopted at boot.
};
static_assert(sizeof(SpecActuatorTunableParams) == 12, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_ACTUATOR_TUNABLE_PARAMS_LAYOUT_HASH = 0xADAA6891U;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_ACTUATOR_TUNABLE_PARAMS_HPP
