// Generated by cdef_gen from the SpecActuator spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Implement the on<Command> hooks in the component (stub-generated).
#ifndef APEX_CDEF_AUTO_SPEC_ACTUATOR_CMD_BASE_HPP
#define APEX_CDEF_AUTO_SPEC_ACTUATOR_CMD_BASE_HPP

#include "src/system/core/infrastructure/system_component/base/inc/SystemComponentStatus.hpp"
#include "src/utilities/compatibility/inc/compat_span.hpp"
#include "MoveRequest_auto.hpp"
#include "PositionResponse_auto.hpp"

#include <cstdint>
#include <cstring>
#include <vector>

namespace appsim {
namespace spec {

/// Spec-generated command dispatch: size-verified decode, hook
/// invocation, response encode. Unknown opcodes fall through to
/// the tier base.
template <typename TBase> class SpecActuatorCmdBase : public TBase {
public:
using TBase::TBase;

protected:
  /// Command a new target position; slew begins next step.
  [[nodiscard]] virtual std::uint8_t onMove(const MoveRequest& request) noexcept = 0;
  /// Stop where we are: target becomes the current position.
  [[nodiscard]] virtual std::uint8_t onHalt() noexcept = 0;
  /// Return the current position and settling state.
  [[nodiscard]] virtual std::uint8_t onGetPosition(PositionResponse& response) noexcept = 0;

[[nodiscard]] std::uint8_t handleCommand(std::uint16_t opcode,
apex::compat::rospan<std::uint8_t> payload,
std::vector<std::uint8_t>& response) noexcept override {
switch (opcode) {
    case 0x0210U: {
      if (payload.size() != sizeof(MoveRequest)) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      MoveRequest request{};
      std::memcpy(&request, payload.data(), sizeof(request));
      return onMove(request);
    }
    case 0x0211U: {
      if (!payload.empty()) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      return onHalt();
    }
    case 0x0212U: {
      if (!payload.empty()) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      PositionResponse reply{};
      const std::uint8_t RC = onGetPosition(reply);
      response.resize(sizeof(reply));
      std::memcpy(response.data(), &reply, sizeof(reply));
      return RC;
    }
    default:
return TBase::handleCommand(opcode, payload, response);
}
}
};

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_ACTUATOR_CMD_BASE_HPP
