// Generated by cdef_gen from the HilDriver spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_DRIVER_STATE_HPP
#define APEX_CDEF_AUTO_DRIVER_STATE_HPP

#include <cstdint>

namespace appsim {
namespace driver {

/// Spec-defined tunable parameters (36 bytes, packed by
/// construction: field order and sizes come from the spec).
struct DriverState {
  std::uint32_t txCount{}; ///< VehicleState frames sent to device.
  std::uint32_t rxCount{}; ///< ControlCmd frames received from device.
  std::uint32_t crcErrors{}; ///< CRC validation failures.
  std::uint32_t txMisses{}; ///< sendState calls skipped (no UART or no state source).
  std::uint32_t rxMisses{}; ///< recvCommand calls with no data available (non-blocking).
  std::uint32_t commLostCount{}; ///< Number of comm loss events.
  std::uint32_t seqGaps{}; ///< Detected gaps in received ControlCmd sequence.
  std::uint16_t txSeq{}; ///< Last sent VehicleState.seqNum.
  std::uint16_t rxSeq{}; ///< Last received ControlCmd.seqNum.
  std::uint8_t hasCmd{}; ///< 1 if a valid ControlCmd has been received.
  std::uint8_t uartOpen{}; ///< 1 if UART is open and configured.
  std::uint8_t commLost{}; ///< 1 if comm watchdog detected link loss.
  std::uint8_t reserved{}; ///< Padding for alignment.
};
static_assert(sizeof(DriverState) == 36, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t DRIVER_STATE_LAYOUT_HASH = 0x400FD0C1U;

} // namespace driver
} // namespace appsim
#endif // APEX_CDEF_AUTO_DRIVER_STATE_HPP
