// Generated by cdef_gen from the SystemMonitor spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SYS_MON_HEALTH_TLM_HPP
#define APEX_CDEF_AUTO_SYS_MON_HEALTH_TLM_HPP

#include <cstddef>
#include <cstdint>

namespace system_core {
namespace support {

/// Spec-defined tunable parameters (88 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SysMonHealthTlm {
  std::uint32_t sampleCount{0};
  std::uint32_t warnCount{0}; ///< Cumulative warning threshold breaches.
  std::uint32_t critCount{0}; ///< Cumulative critical threshold breaches.
  std::uint8_t monitoredCoreCount{0}; ///< Number of valid entries in coreLoad[].
  std::uint8_t pad0{0}; ///< Alignment padding.
  std::int16_t cpuTempC{-1}; ///< CPU temperature (Celsius). -1 = unavailable.
  float coreLoad[16]{};
  float ramUsedPercent{0.0F}; ///< RAM utilization (percent, 0-100).
  std::uint32_t fdCount{0}; ///< Open file descriptor count.
};
static_assert(sizeof(SysMonHealthTlm) == 88, "layout diverged from the spec");
static_assert(offsetof(SysMonHealthTlm, sampleCount) == 0, "field offset diverged");
static_assert(offsetof(SysMonHealthTlm, warnCount) == 4, "field offset diverged");
static_assert(offsetof(SysMonHealthTlm, critCount) == 8, "field offset diverged");
static_assert(offsetof(SysMonHealthTlm, monitoredCoreCount) == 12, "field offset diverged");
static_assert(offsetof(SysMonHealthTlm, pad0) == 13, "field offset diverged");
static_assert(offsetof(SysMonHealthTlm, cpuTempC) == 14, "field offset diverged");
static_assert(offsetof(SysMonHealthTlm, coreLoad) == 16, "field offset diverged");
static_assert(offsetof(SysMonHealthTlm, ramUsedPercent) == 80, "field offset diverged");
static_assert(offsetof(SysMonHealthTlm, fdCount) == 84, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SYS_MON_HEALTH_TLM_LAYOUT_HASH = 0x5A677FA1U;

} // namespace support
} // namespace system_core
#endif // APEX_CDEF_AUTO_SYS_MON_HEALTH_TLM_HPP
