// Generated by cdef_gen from the SystemMonitor spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SYSTEM_MONITOR_TUNABLE_PARAMS_HPP
#define APEX_CDEF_AUTO_SYSTEM_MONITOR_TUNABLE_PARAMS_HPP

#include <cstddef>
#include <cstdint>

namespace system_core {
namespace support {

/// Spec-defined tunable parameters (122 bytes, packed by
/// construction: field order and sizes come from the spec).
struct __attribute__((packed)) SystemMonitorTunableParams {
  float sampleRateHz{1.0F}; ///< Telemetry rate (Hz).
  std::uint8_t cpuEnabled{1}; ///< CPU domain: 1 = enabled, 0 = disabled.
  std::uint8_t monitoredCoreCount{0}; ///< Number of valid entries in monitoredCores.
  std::uint16_t monitoredCores[16]{}; ///< Core indices to monitor.
  float cpuLoadWarnPercent{80.0F}; ///< Per-core load warning threshold.
  float cpuLoadCritPercent{95.0F}; ///< Per-core load critical threshold.
  std::int16_t cpuTempWarnC{75}; ///< CPU temperature warning (Celsius).
  std::int16_t cpuTempCritC{85}; ///< CPU temperature critical (Celsius).
  std::uint32_t cpuRtThrottleWarn{1}; ///< RT throttle delta warning threshold.
  std::uint32_t cpuRtThrottleCrit{10}; ///< RT throttle delta critical threshold.
  std::uint8_t memEnabled{1}; ///< Memory domain: 1 = enabled, 0 = disabled.
  std::uint8_t memPad[3]{}; ///< Explicit padding.
  float memRamWarnPercent{80.0F}; ///< RAM utilization warning threshold.
  float memRamCritPercent{95.0F}; ///< RAM utilization critical threshold.
  std::uint64_t memSwapWarnBytes{1}; ///< Swap usage warning threshold (bytes).
  std::uint64_t memSwapCritBytes{1}; ///< Swap usage critical threshold (bytes).
  float memFdWarnPercent{70.0F}; ///< FD utilization warning threshold.
  float memFdCritPercent{90.0F}; ///< FD utilization critical threshold.
  std::uint8_t gpuEnabled{0}; ///< GPU domain: 1 = enabled, 0 = disabled.
  std::int8_t gpuDeviceIndex{0}; ///< GPU device index.
  std::int16_t gpuTempWarnC{75}; ///< GPU temperature warning (Celsius).
  std::int16_t gpuTempCritC{85}; ///< GPU temperature critical (Celsius).
  std::uint16_t gpuPad{0}; ///< Explicit padding.
  float gpuUtilWarnPercent{90.0F}; ///< GPU utilization warning threshold.
  float gpuUtilCritPercent{98.0F}; ///< GPU utilization critical threshold.
  float gpuMemWarnPercent{80.0F}; ///< GPU memory warning threshold.
  float gpuMemCritPercent{95.0F}; ///< GPU memory critical threshold.
  std::uint8_t gpuThrottleWarnOnAny{1}; ///< 1 = warn on any GPU throttle.
  std::uint8_t gpuPad2[3]{}; ///< Explicit padding.
};
static_assert(sizeof(SystemMonitorTunableParams) == 122, "layout diverged from the spec");
static_assert(offsetof(SystemMonitorTunableParams, sampleRateHz) == 0, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, cpuEnabled) == 4, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, monitoredCoreCount) == 5, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, monitoredCores) == 6, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, cpuLoadWarnPercent) == 38, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, cpuLoadCritPercent) == 42, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, cpuTempWarnC) == 46, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, cpuTempCritC) == 48, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, cpuRtThrottleWarn) == 50, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, cpuRtThrottleCrit) == 54, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, memEnabled) == 58, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, memPad) == 59, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, memRamWarnPercent) == 62, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, memRamCritPercent) == 66, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, memSwapWarnBytes) == 70, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, memSwapCritBytes) == 78, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, memFdWarnPercent) == 86, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, memFdCritPercent) == 90, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, gpuEnabled) == 94, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, gpuDeviceIndex) == 95, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, gpuTempWarnC) == 96, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, gpuTempCritC) == 98, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, gpuPad) == 100, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, gpuUtilWarnPercent) == 102, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, gpuUtilCritPercent) == 106, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, gpuMemWarnPercent) == 110, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, gpuMemCritPercent) == 114, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, gpuThrottleWarnOnAny) == 118, "field offset diverged");
static_assert(offsetof(SystemMonitorTunableParams, gpuPad2) == 119, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SYSTEM_MONITOR_TUNABLE_PARAMS_LAYOUT_HASH = 0xD9C53260U;

} // namespace support
} // namespace system_core
#endif // APEX_CDEF_AUTO_SYSTEM_MONITOR_TUNABLE_PARAMS_HPP
