// Generated by cdef_gen from the SpecProtoMax spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_REPORT_RESPONSE_HPP
#define APEX_CDEF_AUTO_REPORT_RESPONSE_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (8 bytes, packed by
/// construction: field order and sizes come from the spec).
struct ReportResponse {
  std::uint32_t checksum{}; ///< Current checksum.
  std::uint32_t stepCount{}; ///< Steps taken.
};
static_assert(sizeof(ReportResponse) == 8, "layout diverged from the spec");
static_assert(offsetof(ReportResponse, checksum) == 0, "field offset diverged");
static_assert(offsetof(ReportResponse, stepCount) == 4, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t REPORT_RESPONSE_LAYOUT_HASH = 0xABB7323EU;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_REPORT_RESPONSE_HPP
