// Generated by cdef_gen from the SpecProtoMax spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_PROTO_MAX_TUNABLE_PARAMS_HPP
#define APEX_CDEF_AUTO_SPEC_PROTO_MAX_TUNABLE_PARAMS_HPP

#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (80 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecProtoMaxTunableParams {
  double precise{3.141592653589793}; ///< double lane.
  std::uint64_t uWide{9000000000}; ///< uint64 lane.
  std::int64_t iWide{-8000000000}; ///< int64 lane.
  float ratio{0.25F}; ///< float lane.
  std::uint32_t uWord{70000}; ///< uint32 natural-width lane.
  std::int32_t iWord{-70000}; ///< int32 natural-width lane.
  float taps[3]{}; ///< Bounded float array lane.
  std::uint16_t uShort{300}; ///< uint16 via width narrowing.
  std::int16_t iShort{-300}; ///< int16 via width narrowing.
  char tag[8]{}; ///< Bounded string lane (8-byte char buffer, null-padded).
  char aliases[2][4]{}; ///< String array lane (2 x 4-byte char buffers).
  std::uint8_t cookie[4]{}; ///< Byte buffer lane (fixed 4 bytes).
  std::uint8_t uTiny{5}; ///< uint8 via width narrowing.
  std::int8_t iTiny{-5}; ///< int8 via width narrowing.
  bool enabled{true}; ///< bool lane.
  std::uint8_t reserved[5]{}; ///< Tail padding to the struct's 8-byte alignment boundary.
};
static_assert(sizeof(SpecProtoMaxTunableParams) == 80, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_PROTO_MAX_TUNABLE_PARAMS_LAYOUT_HASH = 0xB2F1408CU;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_PROTO_MAX_TUNABLE_PARAMS_HPP
