// Generated by cdef_gen from the SpecChannel spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_CHANNEL_STATE_HPP
#define APEX_CDEF_AUTO_SPEC_CHANNEL_STATE_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (8 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecChannelState {
  float elapsed{}; ///< Seconds since boot (or last Zero).
  std::uint32_t zeros{}; ///< Zero commands handled.
};
static_assert(sizeof(SpecChannelState) == 8, "layout diverged from the spec");
static_assert(offsetof(SpecChannelState, elapsed) == 0, "field offset diverged");
static_assert(offsetof(SpecChannelState, zeros) == 4, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_CHANNEL_STATE_LAYOUT_HASH = 0x9253B2F0U;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_CHANNEL_STATE_HPP
