// Generated by cdef_gen from the SpecChannel spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_CHANNEL_TUNABLE_PARAMS_HPP
#define APEX_CDEF_AUTO_SPEC_CHANNEL_TUNABLE_PARAMS_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (12 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecChannelTunableParams {
  float gain{1.0F}; ///< Ramp slope [units/s].
  float offset{0.0F}; ///< Ramp intercept.
  char channelTag[4]{}; ///< Instance tag for operator displays.
};
static_assert(sizeof(SpecChannelTunableParams) == 12, "layout diverged from the spec");
static_assert(offsetof(SpecChannelTunableParams, gain) == 0, "field offset diverged");
static_assert(offsetof(SpecChannelTunableParams, offset) == 4, "field offset diverged");
static_assert(offsetof(SpecChannelTunableParams, channelTag) == 8, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_CHANNEL_TUNABLE_PARAMS_LAYOUT_HASH = 0x2E5269C1U;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_CHANNEL_TUNABLE_PARAMS_HPP
