// Generated by cdef_gen from the SpecChannel spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_CHANNEL_OUTPUT_HPP
#define APEX_CDEF_AUTO_SPEC_CHANNEL_OUTPUT_HPP

#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (8 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecChannelOutput {
  float value{}; ///< gain * elapsed + offset.
  std::uint32_t sequence{};
};
static_assert(sizeof(SpecChannelOutput) == 8, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_CHANNEL_OUTPUT_LAYOUT_HASH = 0x930F87EAU;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_CHANNEL_OUTPUT_HPP
