// Generated by cdef_gen from the WaveGenerator spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_WAVE_GEN_TUNABLE_PARAMS_HPP
#define APEX_CDEF_AUTO_WAVE_GEN_TUNABLE_PARAMS_HPP

#include <cstdint>

namespace appsim {
namespace wave {

/// Spec-defined tunable parameters (32 bytes, packed by
/// construction: field order and sizes come from the spec).
struct WaveGenTunableParams {
  float frequency{1.0F}; ///< Primary frequency [Hz], range 0..50.
  float amplitude{1.0F}; ///< Peak amplitude, >= 0.
  float dcOffset{0.0F}; ///< DC bias added to output.
  float phaseOffset{0.0F}; ///< Phase offset [radians].
  float noiseAmplitude{0.0F}; ///< Gaussian-like noise peak amplitude.
  float dutyCycle{0.5F}; ///< Duty cycle for SQUARE wave, range 0..1.
  std::uint8_t waveType{0}; ///< WaveType enum value (0=SINE..4=COMPOSITE).
  std::uint8_t reserved[3]{}; ///< Alignment padding.
  float reserved2{0.0F}; ///< Reserved for future use.
};
static_assert(sizeof(WaveGenTunableParams) == 32, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t WAVE_GEN_TUNABLE_PARAMS_LAYOUT_HASH = 0x3C65B01CU;

} // namespace wave
} // namespace appsim
#endif // APEX_CDEF_AUTO_WAVE_GEN_TUNABLE_PARAMS_HPP
