#ifndef APEX_HIL_DEMO_COMPARATOR_DATA_HPP
#define APEX_HIL_DEMO_COMPARATOR_DATA_HPP
/**
 * @file
 * @brief Data structures for the HIL comparator.
 *
 * The struct layouts are spec-defined in comparator_data.toml and generated
 * into .auto/ (regenerated by make cdef, pinned by check-cdef); this
 * header is the stable include point consumers keep using.
 */

#include "demos/apex_hil_demo/support/.auto/ComparatorTunableParams_auto.hpp"
#include "demos/apex_hil_demo/support/.auto/ComparatorState_auto.hpp"

#endif // APEX_HIL_DEMO_COMPARATOR_DATA_HPP
