// Generated by cdef_gen from the DataTransform spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_TRANSFORM_STATS_HPP
#define APEX_CDEF_AUTO_TRANSFORM_STATS_HPP

#include <cstddef>
#include <cstdint>

namespace system_core {
namespace support {

/// Spec-defined tunable parameters (20 bytes, packed by
/// construction: field order and sizes come from the spec).
struct TransformStats {
  std::uint32_t applyCycles{0};
  std::uint32_t masksApplied{0}; ///< Successful mask applications.
  std::uint32_t resolveFailures{0}; ///< Target resolution failures.
  std::uint32_t applyFailures{0}; ///< Mask application failures.
  std::uint32_t entriesArmed{0}; ///< Currently armed entry count.
};
static_assert(sizeof(TransformStats) == 20, "layout diverged from the spec");
static_assert(offsetof(TransformStats, applyCycles) == 0, "field offset diverged");
static_assert(offsetof(TransformStats, masksApplied) == 4, "field offset diverged");
static_assert(offsetof(TransformStats, resolveFailures) == 8, "field offset diverged");
static_assert(offsetof(TransformStats, applyFailures) == 12, "field offset diverged");
static_assert(offsetof(TransformStats, entriesArmed) == 16, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t TRANSFORM_STATS_LAYOUT_HASH = 0x1BCD6174U;

} // namespace support
} // namespace system_core
#endif // APEX_CDEF_AUTO_TRANSFORM_STATS_HPP
