/**
 * @file 01_HorizonProceduralGravity_dTest.cpp
 * @brief Integration test: load horizon-generated procedural gravity .bin
 *        through Apex's existing SphericalHarmonicModel + GravityCoeffTable.
 *
 * Goals:
 *  - Verify the horizon procedural pipeline emits an apex-readable
 *    36-byte-record .bin (wire-format compatibility check).
 *  - Initialize SphericalHarmonicModel against an arbitrary fictional
 *    body's params (alpha: GM=3.5e14, R=6e6, N=60) -- no Earth-specific
 *    coupling.
 *  - Validate acceleration computation at orbital altitude:
 *      |a| ~ GM/r^2 to within harmonic perturbations
 *      a is finite (no NaN/Inf)
 *      a points roughly toward the body center (radially inward)
 *
 * Prereqs:
 *  - alpha_grav_n60.bin in data/procedural/, generated by:
 *      horizon_world gen-gravity \
 *          --spec tools/world_data/samples/alpha.toml \
 *          --out alpha_grav_n60.bin
 *
 * Notes:
 *  - Test SKIPs cleanly if the fixture is absent (so dev runs without
 *    horizon checked out side-by-side still work).
 *  - Run manually:
 *      ./build/hosted-x86_64-debug/bin/devtests/SimEnvironmentGravity_Dev \
 *          --gtest_filter="HorizonProceduralGravity*"
 */

#include <gtest/gtest.h>

#include "src/sim/environment/gravity/inc/CoeffSource.hpp"
#include "src/sim/environment/gravity/inc/FullTableCoeffSource.hpp"
#include "src/sim/environment/gravity/inc/SphericalHarmonicModel.hpp"

#include <cmath>
#include <iomanip>
#include <iostream>

using sim::environment::gravity::FullTableCoeffSource;
using sim::environment::gravity::SphericalHarmonicModel;
using sim::environment::gravity::SphericalHarmonicParams;

namespace {

/* ----------------------------- Test Configuration ----------------------------- */

/// Path to horizon-generated procedural gravity table for body "alpha".
/// Relative to apex_csf workspace root (where ctest runs from).
constexpr const char* K_ALPHA_TABLE_PATH =
    "src/sim/environment/gravity/data/procedural/alpha_grav_n60.bin";

/// Body params for "alpha" (from horizon's tools/world_data/samples/alpha.toml).
constexpr double ALPHA_GM = 3.5e14;     // m^3 / s^2
constexpr double ALPHA_R = 6'000'000.0; // m (equatorial radius)
constexpr std::int16_t ALPHA_N_MAX = 60;

/// Test point: 400 km altitude over the +x axis (equatorial).
constexpr double TEST_ALT_M = 400'000.0;
constexpr double TEST_R = ALPHA_R + TEST_ALT_M;

} // namespace

/* ----------------------------- Tests ----------------------------- */

/**
 * @test TableLoadsProcedural
 * @brief Verify horizon's procedural .bin is openable + structurally
 *        consistent with apex's reader expectations.
 */
TEST(HorizonProceduralGravity, TableLoadsProcedural) {
  std::cout << "\n=== Horizon procedural gravity: table load ===\n";

  FullTableCoeffSource src;
  if (!src.open(K_ALPHA_TABLE_PATH)) {
    GTEST_SKIP() << "procedural fixture not present: " << K_ALPHA_TABLE_PATH
                 << "  (generate with horizon_world gen-gravity --spec alpha.toml)";
  }

  std::cout << "  min degree: " << src.minDegree() << "\n";
  std::cout << "  max degree: " << src.maxDegree() << "\n";

  // Horizon emits records starting at n=0, unlike EGM2008's n=2-start.
  EXPECT_EQ(src.minDegree(), 0);
  EXPECT_EQ(src.maxDegree(), ALPHA_N_MAX);

  // C_00 = 1 (unit total mass) -- the procedural pipeline writes this exactly.
  double c00 = 0;
  double s00 = 0;
  ASSERT_TRUE(src.get(0, 0, c00, s00));
  EXPECT_DOUBLE_EQ(c00, 1.0);
  EXPECT_DOUBLE_EQ(s00, 0.0);

  // C_20 < 0 (J2 oblateness signature from omega/R/GM injection).
  double c20 = 0;
  double s20 = 0;
  ASSERT_TRUE(src.get(2, 0, c20, s20));
  std::cout << "  C_20 (J2 sig): " << std::scientific << c20 << "\n";
  EXPECT_LT(c20, 0.0);
  EXPECT_GT(c20, -1e-2); // reasonable magnitude

  // n=1 terms are exactly 0 (CoM at origin).
  double c10 = 0, s10 = 0, c11 = 0, s11 = 0;
  ASSERT_TRUE(src.get(1, 0, c10, s10));
  ASSERT_TRUE(src.get(1, 1, c11, s11));
  EXPECT_DOUBLE_EQ(c10, 0.0);
  EXPECT_DOUBLE_EQ(c11, 0.0);
  EXPECT_DOUBLE_EQ(s11, 0.0);
}

/**
 * @test ModelInits
 * @brief Initialize SphericalHarmonicModel with alpha's body params.
 *        Confirms the body-agnostic init path works on procedural data.
 */
TEST(HorizonProceduralGravity, ModelInits) {
  FullTableCoeffSource src;
  if (!src.open(K_ALPHA_TABLE_PATH)) {
    GTEST_SKIP() << "procedural fixture not present";
  }

  SphericalHarmonicModel model;
  SphericalHarmonicParams params{ALPHA_GM, ALPHA_R, ALPHA_N_MAX};
  ASSERT_TRUE(model.init(src, params));
  EXPECT_EQ(model.maxDegree(), ALPHA_N_MAX);
}

/**
 * @test AccelerationAtOrbit
 * @brief Compute acceleration at a 400-km-altitude point over +x.
 *        Validate magnitude near GM/r^2 and direction roughly radially inward.
 */
TEST(HorizonProceduralGravity, AccelerationAtOrbit) {
  std::cout << "\n=== Horizon procedural gravity: orbital acceleration ===\n";

  FullTableCoeffSource src;
  if (!src.open(K_ALPHA_TABLE_PATH)) {
    GTEST_SKIP() << "procedural fixture not present";
  }

  SphericalHarmonicModel model;
  SphericalHarmonicParams params{ALPHA_GM, ALPHA_R, ALPHA_N_MAX};
  ASSERT_TRUE(model.init(src, params));

  // Point at +x, altitude 400 km above alpha's surface.
  const double r_bf[3] = {TEST_R, 0.0, 0.0};
  double a_bf[3] = {0.0, 0.0, 0.0};
  ASSERT_TRUE(model.acceleration(r_bf, a_bf));

  // No NaN/Inf.
  EXPECT_TRUE(std::isfinite(a_bf[0]));
  EXPECT_TRUE(std::isfinite(a_bf[1]));
  EXPECT_TRUE(std::isfinite(a_bf[2]));

  const double A_MAG = std::sqrt(a_bf[0] * a_bf[0] + a_bf[1] * a_bf[1] + a_bf[2] * a_bf[2]);
  const double EXPECTED_POINT_MASS = ALPHA_GM / (TEST_R * TEST_R);

  std::cout << "  test point   = (" << TEST_R / 1000.0 << " km, 0, 0)\n";
  std::cout << "  GM/r^2       = " << EXPECTED_POINT_MASS << " m/s^2\n";
  std::cout << "  |a| computed = " << A_MAG << " m/s^2\n";
  std::cout << "  a            = (" << a_bf[0] << ", " << a_bf[1] << ", " << a_bf[2] << ")\n";

  // At LEO altitude, harmonic terms are O(1e-3) relative to point-mass.
  // So |a| should match GM/r^2 within ~1%.
  EXPECT_NEAR(A_MAG, EXPECTED_POINT_MASS, 0.01 * EXPECTED_POINT_MASS);

  // Acceleration is roughly radially inward (toward origin from +x).
  // a_x should be the dominant component and negative.
  EXPECT_LT(a_bf[0], 0.0);
  EXPECT_GT(std::abs(a_bf[0]), std::abs(a_bf[1]));
  EXPECT_GT(std::abs(a_bf[0]), std::abs(a_bf[2]));
}

/**
 * @test AccelerationOverPole
 * @brief Compute acceleration over the +z axis. With J2 injection, the
 *        magnitude should differ slightly from the equatorial point at the
 *        same r (oblateness signature on the gravity field).
 */
TEST(HorizonProceduralGravity, AccelerationOverPole) {
  FullTableCoeffSource src;
  if (!src.open(K_ALPHA_TABLE_PATH)) {
    GTEST_SKIP() << "procedural fixture not present";
  }

  SphericalHarmonicModel model;
  SphericalHarmonicParams params{ALPHA_GM, ALPHA_R, ALPHA_N_MAX};
  ASSERT_TRUE(model.init(src, params));

  const double r_eq[3] = {TEST_R, 0.0, 0.0};
  const double r_pol[3] = {0.0, 0.0, TEST_R};
  double a_eq[3] = {0.0, 0.0, 0.0};
  double a_pol[3] = {0.0, 0.0, 0.0};
  ASSERT_TRUE(model.acceleration(r_eq, a_eq));
  ASSERT_TRUE(model.acceleration(r_pol, a_pol));

  const double MAG_EQ = std::sqrt(a_eq[0] * a_eq[0] + a_eq[1] * a_eq[1] + a_eq[2] * a_eq[2]);
  const double MAG_POL = std::sqrt(a_pol[0] * a_pol[0] + a_pol[1] * a_pol[1] + a_pol[2] * a_pol[2]);

  // Both finite + same order of magnitude.
  EXPECT_TRUE(std::isfinite(MAG_EQ));
  EXPECT_TRUE(std::isfinite(MAG_POL));
  EXPECT_NEAR(MAG_EQ, MAG_POL, 0.01 * MAG_EQ);

  std::cout << "\n=== Horizon procedural gravity: equator vs pole ===\n";
  std::cout << "  |a| equator = " << std::scientific << MAG_EQ << " m/s^2\n";
  std::cout << "  |a| pole    = " << std::scientific << MAG_POL << " m/s^2\n";
  std::cout << "  ratio        = " << MAG_POL / MAG_EQ << "\n";
}
