// Generated by cdef_gen from the HilPlantModel spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_HIL_PLANT_STATE_HPP
#define APEX_CDEF_AUTO_HIL_PLANT_STATE_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace plant {

/// Spec-defined tunable parameters (56 bytes, packed by
/// construction: field order and sizes come from the spec).
struct HilPlantState {
  double simTime{}; ///< Elapsed simulation time [s].
  double lastAlt{}; ///< Last computed altitude [m].
  double lastVz{}; ///< Last vertical velocity [m/s].
  std::uint32_t stepCount{}; ///< Plant steps executed.
  std::uint32_t ctrlCount{}; ///< Control updates executed.
  std::uint32_t tlmCount{}; ///< Telemetry reports sent.
  std::uint32_t commLossCount{}; ///< Comm loss events detected.
  std::uint32_t staleCmdFrames{}; ///< Consecutive control frames with no new command.
  std::uint32_t lastSeenRxCount{}; ///< Snapshot of driver rxCount for staleness detection.
  std::uint8_t commLost{}; ///< 1 if currently in comm loss state.
  std::uint8_t reserved[7]{}; ///< Padding for 8-byte alignment.
};
static_assert(sizeof(HilPlantState) == 56, "layout diverged from the spec");
static_assert(offsetof(HilPlantState, simTime) == 0, "field offset diverged");
static_assert(offsetof(HilPlantState, lastAlt) == 8, "field offset diverged");
static_assert(offsetof(HilPlantState, lastVz) == 16, "field offset diverged");
static_assert(offsetof(HilPlantState, stepCount) == 24, "field offset diverged");
static_assert(offsetof(HilPlantState, ctrlCount) == 28, "field offset diverged");
static_assert(offsetof(HilPlantState, tlmCount) == 32, "field offset diverged");
static_assert(offsetof(HilPlantState, commLossCount) == 36, "field offset diverged");
static_assert(offsetof(HilPlantState, staleCmdFrames) == 40, "field offset diverged");
static_assert(offsetof(HilPlantState, lastSeenRxCount) == 44, "field offset diverged");
static_assert(offsetof(HilPlantState, commLost) == 48, "field offset diverged");
static_assert(offsetof(HilPlantState, reserved) == 49, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t HIL_PLANT_STATE_LAYOUT_HASH = 0xEC84014FU;

} // namespace plant
} // namespace appsim
#endif // APEX_CDEF_AUTO_HIL_PLANT_STATE_HPP
