// Generated by cdef_gen from the HilPlantModel spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_HIL_PLANT_TUNABLE_PARAMS_HPP
#define APEX_CDEF_AUTO_HIL_PLANT_TUNABLE_PARAMS_HPP

#include <cstdint>

namespace appsim {
namespace plant {

/// Spec-defined tunable parameters (64 bytes, packed by
/// construction: field order and sizes come from the spec).
struct HilPlantTunableParams {
  double mass{10.0}; ///< Vehicle mass [kg].
  double dragCd{0.5}; ///< Drag coefficient.
  double dragArea{0.1}; ///< Reference area [m^2].
  double targetAlt{100.0}; ///< PD controller target altitude [m].
  double ctrlKp{2.0}; ///< Proportional gain [N/m].
  double ctrlKd{1.5}; ///< Derivative gain [N/(m/s)].
  double thrustMax{200.0}; ///< Maximum thrust magnitude [N].
  double commLossFrames{25.0}; ///< Control frames without new cmd before comm loss (0=disabled).
};
static_assert(sizeof(HilPlantTunableParams) == 64, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t HIL_PLANT_TUNABLE_PARAMS_LAYOUT_HASH = 0x2D523611U;

} // namespace plant
} // namespace appsim
#endif // APEX_CDEF_AUTO_HIL_PLANT_TUNABLE_PARAMS_HPP
