// Generated by cdef_gen from the VirtualFlightCtrl spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_VFC_STATE_HPP
#define APEX_CDEF_AUTO_VFC_STATE_HPP

#include <cstdint>

namespace appsim {
namespace model {

/// Spec-defined tunable parameters (16 bytes, packed by
/// construction: field order and sizes come from the spec).
struct VfcState {
  std::uint32_t rxCount{}; ///< Valid VehicleState frames received.
  std::uint32_t txCount{}; ///< ControlCmd frames sent.
  std::uint32_t crcErrors{}; ///< CRC validation failures.
  std::uint32_t pollCount{}; ///< Transport poll iterations.
};
static_assert(sizeof(VfcState) == 16, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t VFC_STATE_LAYOUT_HASH = 0x5A9B1590U;

} // namespace model
} // namespace appsim
#endif // APEX_CDEF_AUTO_VFC_STATE_HPP
