// Generated by cdef_gen from the SpecBusDriver spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_BUS_STATS_HPP
#define APEX_CDEF_AUTO_BUS_STATS_HPP

#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (16 bytes, packed by
/// construction: field order and sizes come from the spec).
struct BusStats {
  std::uint32_t txFrames{};
  std::uint32_t rxFrames{};
  std::uint32_t txBytes{};
  std::uint32_t rxBytes{};
};
static_assert(sizeof(BusStats) == 16, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t BUS_STATS_LAYOUT_HASH = 0x258BEC42U;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_BUS_STATS_HPP
