// Generated by cdef_gen from the SpecBusDriver spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_BUS_DRIVER_OUTPUT_HPP
#define APEX_CDEF_AUTO_SPEC_BUS_DRIVER_OUTPUT_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (8 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecBusDriverOutput {
  std::uint32_t rxFrames{}; ///< Received-frame counter (published).
  std::uint8_t lastRxLen{}; ///< Length of the last received frame [bytes].
  std::uint8_t reserved[3]{};
};
static_assert(sizeof(SpecBusDriverOutput) == 8, "layout diverged from the spec");
static_assert(offsetof(SpecBusDriverOutput, rxFrames) == 0, "field offset diverged");
static_assert(offsetof(SpecBusDriverOutput, lastRxLen) == 4, "field offset diverged");
static_assert(offsetof(SpecBusDriverOutput, reserved) == 5, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_BUS_DRIVER_OUTPUT_LAYOUT_HASH = 0xBE351D97U;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_BUS_DRIVER_OUTPUT_HPP
