// Generated by cdef_gen from the SpecBusDriver spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Implement the on<Command> hooks in the component (stub-generated).
#ifndef APEX_CDEF_AUTO_SPEC_BUS_DRIVER_CMD_BASE_HPP
#define APEX_CDEF_AUTO_SPEC_BUS_DRIVER_CMD_BASE_HPP

#include "src/system/core/infrastructure/system_component/base/inc/SystemComponentStatus.hpp"
#include "src/utilities/compatibility/inc/compat_span.hpp"
#include "FrameRequest_auto.hpp"
#include "BusStats_auto.hpp"

#include <cstdint>
#include <cstring>
#include <vector>

namespace appsim {
namespace spec {

/// Spec-generated command dispatch: size-verified decode, hook
/// invocation, response encode. Unknown opcodes fall through to
/// the tier base.
template <typename TBase> class SpecBusDriverCmdBase : public TBase {
public:
using TBase::TBase;

protected:
  /// Queue a frame on the loopback bus.
  [[nodiscard]] virtual std::uint8_t onSendFrame(const FrameRequest& request) noexcept = 0;
  /// Drop any pending frame.
  [[nodiscard]] virtual std::uint8_t onFlush() noexcept = 0;
  /// Return the traffic counters.
  [[nodiscard]] virtual std::uint8_t onGetStats(BusStats& response) noexcept = 0;

[[nodiscard]] std::uint8_t handleCommand(std::uint16_t opcode,
apex::compat::rospan<std::uint8_t> payload,
std::vector<std::uint8_t>& response) noexcept override {
switch (opcode) {
    case 0x0220U: {
      if (payload.size() != sizeof(FrameRequest)) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      FrameRequest request{};
      std::memcpy(&request, payload.data(), sizeof(request));
      return onSendFrame(request);
    }
    case 0x0221U: {
      if (!payload.empty()) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      return onFlush();
    }
    case 0x0222U: {
      if (!payload.empty()) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      BusStats reply{};
      const std::uint8_t RC = onGetStats(reply);
      response.resize(sizeof(reply));
      std::memcpy(response.data(), &reply, sizeof(reply));
      return RC;
    }
    default:
return TBase::handleCommand(opcode, payload, response);
}
}
};

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_BUS_DRIVER_CMD_BASE_HPP
