// Generated by cdef_gen from the SpecBusDriver spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_BUS_DRIVER_TUNABLE_PARAMS_HPP
#define APEX_CDEF_AUTO_SPEC_BUS_DRIVER_TUNABLE_PARAMS_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (4 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecBusDriverTunableParams {
  std::uint16_t loopDelayTicks{1}; ///< Steps a frame sits on the loopback before it is received.
  std::uint8_t maxFrameBytes{16}; ///< Largest accepted frame length [bytes].
  std::uint8_t reserved{};
};
static_assert(sizeof(SpecBusDriverTunableParams) == 4, "layout diverged from the spec");
static_assert(offsetof(SpecBusDriverTunableParams, loopDelayTicks) == 0, "field offset diverged");
static_assert(offsetof(SpecBusDriverTunableParams, maxFrameBytes) == 2, "field offset diverged");
static_assert(offsetof(SpecBusDriverTunableParams, reserved) == 3, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_BUS_DRIVER_TUNABLE_PARAMS_LAYOUT_HASH = 0xBABA083FU;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_BUS_DRIVER_TUNABLE_PARAMS_HPP
