// Generated by cdef_gen from the SensorModel spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SENSOR_TUNABLE_PARAMS_HPP
#define APEX_CDEF_AUTO_SENSOR_TUNABLE_PARAMS_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace sensor {

/// Spec-defined tunable parameters (12 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SensorTunableParams {
  float rampRate{0.5F}; ///< Temperature increase per step [deg/step].
  float initialTemp{20.0F}; ///< Starting temperature [deg].
  float maxTemp{120.0F}; ///< Wrap-around temperature (resets to initial).
};
static_assert(sizeof(SensorTunableParams) == 12, "layout diverged from the spec");
static_assert(offsetof(SensorTunableParams, rampRate) == 0, "field offset diverged");
static_assert(offsetof(SensorTunableParams, initialTemp) == 4, "field offset diverged");
static_assert(offsetof(SensorTunableParams, maxTemp) == 8, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SENSOR_TUNABLE_PARAMS_LAYOUT_HASH = 0x4A9E522FU;

} // namespace sensor
} // namespace appsim
#endif // APEX_CDEF_AUTO_SENSOR_TUNABLE_PARAMS_HPP
