// Generated by cdef_gen from the SensorModel spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SENSOR_OUTPUT_HPP
#define APEX_CDEF_AUTO_SENSOR_OUTPUT_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace sensor {

/// Spec-defined tunable parameters (12 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SensorOutput {
  float temperature{0.0F}; ///< Current temperature reading [deg].
  float temperatureRate{0.0F}; ///< Rate of change [deg/step].
  std::uint8_t overtemp{}; ///< 1 if temperature > 100.0 (threshold).
  std::uint8_t reserved[3]{}; ///< Alignment padding.
};
static_assert(sizeof(SensorOutput) == 12, "layout diverged from the spec");
static_assert(offsetof(SensorOutput, temperature) == 0, "field offset diverged");
static_assert(offsetof(SensorOutput, temperatureRate) == 4, "field offset diverged");
static_assert(offsetof(SensorOutput, overtemp) == 8, "field offset diverged");
static_assert(offsetof(SensorOutput, reserved) == 9, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SENSOR_OUTPUT_LAYOUT_HASH = 0xF9B53AAFU;

} // namespace sensor
} // namespace appsim
#endif // APEX_CDEF_AUTO_SENSOR_OUTPUT_HPP
