// Generated by cdef_gen from the SensorModel spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SENSOR_STATE_HPP
#define APEX_CDEF_AUTO_SENSOR_STATE_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace sensor {

/// Spec-defined tunable parameters (8 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SensorState {
  std::uint32_t stepCount{}; ///< Total step invocations.
  std::uint32_t wrapCount{}; ///< Number of temperature wrap-arounds.
};
static_assert(sizeof(SensorState) == 8, "layout diverged from the spec");
static_assert(offsetof(SensorState, stepCount) == 0, "field offset diverged");
static_assert(offsetof(SensorState, wrapCount) == 4, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SENSOR_STATE_LAYOUT_HASH = 0xAB1015BDU;

} // namespace sensor
} // namespace appsim
#endif // APEX_CDEF_AUTO_SENSOR_STATE_HPP
