// Generated by cdef_gen from the SpecMatrix spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_MATRIX_SNAPSHOT_HPP
#define APEX_CDEF_AUTO_MATRIX_SNAPSHOT_HPP

#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (8 bytes, packed by
/// construction: field order and sizes come from the spec).
struct MatrixSnapshot {
  std::uint32_t checksum{};
  std::uint32_t stepCount{};
};
static_assert(sizeof(MatrixSnapshot) == 8, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t MATRIX_SNAPSHOT_LAYOUT_HASH = 0x7E448D88U;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_MATRIX_SNAPSHOT_HPP
