// Generated by cdef_gen from the SpecMatrix spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Implement the on<Command> hooks in the component (stub-generated).
#ifndef APEX_CDEF_AUTO_SPEC_MATRIX_CMD_BASE_HPP
#define APEX_CDEF_AUTO_SPEC_MATRIX_CMD_BASE_HPP

#include "src/system/core/infrastructure/system_component/base/inc/SystemComponentStatus.hpp"
#include "src/utilities/compatibility/inc/compat_span.hpp"
#include "MatrixSnapshot_auto.hpp"

#include <cstdint>
#include <cstring>
#include <vector>

namespace appsim {
namespace spec {

/// Spec-generated command dispatch: size-verified decode, hook
/// invocation, response encode. Unknown opcodes fall through to
/// the tier base.
template <typename TBase> class SpecMatrixCmdBase : public TBase {
public:
using TBase::TBase;

protected:
  /// Return the current checksum and step count.
  [[nodiscard]] virtual std::uint8_t onGetSnapshot(MatrixSnapshot& response) noexcept = 0;

[[nodiscard]] std::uint8_t handleCommand(std::uint16_t opcode,
apex::compat::rospan<std::uint8_t> payload,
std::vector<std::uint8_t>& response) noexcept override {
switch (opcode) {
    case 0x0230U: {
      if (!payload.empty()) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      MatrixSnapshot reply{};
      const std::uint8_t RC = onGetSnapshot(reply);
      response.resize(sizeof(reply));
      std::memcpy(response.data(), &reply, sizeof(reply));
      return RC;
    }
    default:
return TBase::handleCommand(opcode, payload, response);
}
}
};

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_MATRIX_CMD_BASE_HPP
