// Generated by cdef_gen from the SpecMatrix spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_MATRIX_TUNABLE_PARAMS_HPP
#define APEX_CDEF_AUTO_SPEC_MATRIX_TUNABLE_PARAMS_HPP

#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (80 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecMatrixTunableParams {
  std::int64_t iWide{-8000000000}; ///< int64 lane.
  std::uint64_t uWide{9000000000}; ///< uint64 lane.
  double precise{2.718281828}; ///< double lane.
  std::int32_t iWord{-70000}; ///< int32 lane.
  std::uint32_t uWord{70000}; ///< uint32 lane.
  float ratio{0.5F}; ///< float lane.
  std::uint16_t gains[4]{}; ///< uint16 array lane.
  std::int16_t iShort{-300}; ///< int16 lane.
  std::uint16_t uShort{300}; ///< uint16 lane.
  std::int8_t iTiny{-5}; ///< int8 lane.
  std::uint8_t uTiny{5}; ///< uint8 lane.
  bool enabled{true}; ///< bool lane.
  char label[12]{}; ///< Bounded string lane (12-byte char buffer).
  char tags[2][6]{}; ///< String array lane (2 x 6-byte char buffers).
  std::uint8_t blob[5]{}; ///< Byte buffer lane.
};
static_assert(sizeof(SpecMatrixTunableParams) == 80, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_MATRIX_TUNABLE_PARAMS_LAYOUT_HASH = 0x5D6CD6BAU;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_MATRIX_TUNABLE_PARAMS_HPP
