// Generated by cdef_gen from the SpecMatrix spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_MATRIX_STATE_HPP
#define APEX_CDEF_AUTO_SPEC_MATRIX_STATE_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (8 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecMatrixState {
  std::uint32_t stepCount{};
  std::uint32_t checksum{}; ///< Running XOR over the tunable bytes, recomputed each step.
};
static_assert(sizeof(SpecMatrixState) == 8, "layout diverged from the spec");
static_assert(offsetof(SpecMatrixState, stepCount) == 0, "field offset diverged");
static_assert(offsetof(SpecMatrixState, checksum) == 4, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_MATRIX_STATE_LAYOUT_HASH = 0xEC80FB62U;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_MATRIX_STATE_HPP
