#ifndef APEX_HIL_DEMO_DRIVER_DATA_HPP
#define APEX_HIL_DEMO_DRIVER_DATA_HPP
/**
 * @file
 * @brief Data structures for the HIL UART driver.
 *
 * The struct layouts are spec-defined in driver_data.toml and generated
 * into .auto/ (regenerated by make cdef, pinned by check-cdef); this
 * header is the stable include point consumers keep using.
 */

#include "demos/apex_hil_demo/driver/.auto/DriverState_auto.hpp"

#endif // APEX_HIL_DEMO_DRIVER_DATA_HPP
