#ifndef APEX_HIL_DEMO_PLANT_DATA_HPP
#define APEX_HIL_DEMO_PLANT_DATA_HPP
/**
 * @file
 * @brief Data structures for the HIL plant model.
 *
 * The struct layouts are spec-defined in plant_data.toml and generated
 * into .auto/ (regenerated by make cdef, pinned by check-cdef); this
 * header is the stable include point consumers keep using.
 */

#include "demos/apex_hil_demo/model/.auto/HilPlantTunableParams_auto.hpp"
#include "demos/apex_hil_demo/model/.auto/HilPlantState_auto.hpp"

#endif // APEX_HIL_DEMO_PLANT_DATA_HPP
