#ifndef APEX_HIL_DEMO_VIRTUAL_FLIGHT_CTRL_DATA_HPP
#define APEX_HIL_DEMO_VIRTUAL_FLIGHT_CTRL_DATA_HPP
/**
 * @file
 * @brief Data structures for the virtual flight controller.
 *
 * The struct layouts are spec-defined in vfc_data.toml and generated
 * into .auto/ (regenerated by make cdef, pinned by check-cdef); this
 * header is the stable include point consumers keep using.
 */

#include "demos/apex_hil_demo/model/.auto/VfcState_auto.hpp"

#endif // APEX_HIL_DEMO_VIRTUAL_FLIGHT_CTRL_DATA_HPP
