// Generated by cdef_gen from the SpecLimits spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_NUDGE_REQUEST_HPP
#define APEX_CDEF_AUTO_NUDGE_REQUEST_HPP

#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (4 bytes, packed by
/// construction: field order and sizes come from the spec).
struct NudgeRequest {
  float delta{}; ///< Added to value; results outside the banded rail reject.
};
static_assert(sizeof(NudgeRequest) == 4, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t NUDGE_REQUEST_LAYOUT_HASH = 0x716D14C3U;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_NUDGE_REQUEST_HPP
