// Generated by cdef_gen from the SpecLimits spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_LIMITS_STATE_HPP
#define APEX_CDEF_AUTO_SPEC_LIMITS_STATE_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (12 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecLimitsState {
  float value{}; ///< Accumulated nudges, clamped to the banded rail.
  std::uint32_t nudges{};
  std::uint32_t rejects{};
};
static_assert(sizeof(SpecLimitsState) == 12, "layout diverged from the spec");
static_assert(offsetof(SpecLimitsState, value) == 0, "field offset diverged");
static_assert(offsetof(SpecLimitsState, nudges) == 4, "field offset diverged");
static_assert(offsetof(SpecLimitsState, rejects) == 8, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_LIMITS_STATE_LAYOUT_HASH = 0x508291FCU;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_LIMITS_STATE_HPP
