// Generated by cdef_gen from the SpecLimits spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Implement the on<Command> hooks in the component (stub-generated).
#ifndef APEX_CDEF_AUTO_SPEC_LIMITS_CMD_BASE_HPP
#define APEX_CDEF_AUTO_SPEC_LIMITS_CMD_BASE_HPP

#include "src/system/core/infrastructure/system_component/base/inc/SystemComponentStatus.hpp"
#include "src/utilities/compatibility/inc/compat_span.hpp"
#include "NudgeRequest_auto.hpp"

#include <cstdint>
#include <cstring>
#include <vector>

namespace appsim {
namespace spec {

/// Spec-generated command dispatch: size-verified decode, hook
/// invocation, response encode. Unknown opcodes fall through to
/// the tier base.
template <typename TBase> class SpecLimitsCmdBase : public TBase {
public:
using TBase::TBase;

protected:
  /// Nudge the value; out-of-band results reject and count.
  [[nodiscard]] virtual std::uint8_t onNudge(const NudgeRequest& request) noexcept = 0;

[[nodiscard]] std::uint8_t handleCommand(std::uint16_t opcode,
apex::compat::rospan<std::uint8_t> payload,
std::vector<std::uint8_t>& response) noexcept override {
switch (opcode) {
    case 0x0238U: {
      if (payload.size() != sizeof(NudgeRequest)) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      NudgeRequest request{};
      std::memcpy(&request, payload.data(), sizeof(request));
      return onNudge(request);
    }
    default:
return TBase::handleCommand(opcode, payload, response);
}
}
};

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_LIMITS_CMD_BASE_HPP
