// Generated by cdef_gen from the SpecLimits spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_LIMITS_TUNABLE_PARAMS_HPP
#define APEX_CDEF_AUTO_SPEC_LIMITS_TUNABLE_PARAMS_HPP

#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (36 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecLimitsTunableParams {
  float floorOnly{1.0F}; ///< min-only rail.
  float ceilOnly{50.0F}; ///< max-only rail.
  float banded{5.0F}; ///< min+max rail.
  float stepped{0.75F}; ///< step rail (granularity 0.25 from 0).
  float gainTable[4]{}; ///< Array rail: every element inherits the same band.
  std::uint8_t mode{3}; ///< allowed-list rail (odd modes only).
  std::uint8_t reserved[3]{};
};
static_assert(sizeof(SpecLimitsTunableParams) == 36, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_LIMITS_TUNABLE_PARAMS_LAYOUT_HASH = 0xEA32365DU;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_LIMITS_TUNABLE_PARAMS_HPP
