// Generated by cdef_gen from the SpecLimits spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Implement the task methods and on<Command> hooks in the component
// (stub-generated); the base owns members, loadTprm, doInit, dispatch.
#ifndef APEX_CDEF_AUTO_SPEC_LIMITS_SPEC_BASE_HPP
#define APEX_CDEF_AUTO_SPEC_LIMITS_SPEC_BASE_HPP

#include "src/system/core/infrastructure/system_component/base/inc/SystemComponentStatus.hpp"
#include "src/utilities/compatibility/inc/compat_span.hpp"
#include "src/system/core/infrastructure/system_component/posix/inc/ParamBank.hpp"
#include "src/system/core/infrastructure/system_component/posix/inc/ModelData.hpp"
#include <filesystem>
#include "NudgeRequest_auto.hpp"
#include "SpecLimitsTunableParams_auto.hpp"
#include "SpecLimitsState_auto.hpp"

#include <cstdint>
#include <cstring>
#include <vector>

namespace appsim {
namespace spec {

/// Spec-generated component base (CRTP over the derived component
/// and its tier base): owns the categorized data members, the
/// hash-enforcing loadTprm, the [[tasks]]-driven doInit, and the
/// command dispatch. Unknown opcodes fall through to the tier base.
template <typename TDerived, typename TBase> class SpecLimitsSpecBase : public TBase {
public:
using TBase::TBase;

  enum class TaskUid : std::uint8_t {
    STEP = 1, ///< 10 Hz tick (the model is command-driven).
  };

  [[nodiscard]] const SpecLimitsState& state() const noexcept { return state_.get(); }

  system_core::system_component::TprmIngest
  loadTprm(const std::filesystem::path& tprmDir) noexcept override {
    using system_core::system_component::TprmIngest;
    if (!this->isRegistered()) {
      return TprmIngest::REJECTED;
    }
    const std::filesystem::path PATH = tprmDir / this->tprmFilename(this->fullUid());
    const bool PRESENT = std::filesystem::exists(PATH);
    bool loaded = false;
    if (PRESENT) {
      loaded = paramBank_.load(
                   PATH, this->fullUid(),
                   [this](const SpecLimitsTunableParams& p) noexcept { return validateParams(p); },
                   &SPEC_LIMITS_TUNABLE_PARAMS_LAYOUT_HASH) ==
               system_core::system_component::Status::SUCCESS;
    }
    if (!loaded) {
      (void)paramBank_.load(SpecLimitsTunableParams{});
    }
    // First load publishes the initial generation; a RELOAD on a
    // live bank must APPLY the staged set instead -- publishInitial
    // is a no-op once a generation is active (silent-no-effect
    // defect class, caught by zenith 2026-08-22).
    if (paramBank_.activeGeneration() == 0) {
      (void)paramBank_.publishInitial();
    } else {
      (void)paramBank_.apply();
    }
    inspectParams_ = paramBank_.active();
    onParamsLoaded();
    this->setConfigured(true);
    if (loaded) {
      return TprmIngest::LOADED;
    }
    return PRESENT ? TprmIngest::REJECTED : TprmIngest::DEFAULTS;
  }

  /// Staged-payload verification enforces the spec hash for this
  /// component (VERIFY_TPRM and the verify-gated RELOAD).
  [[nodiscard]] const std::uint32_t* expectedLayoutHash() const noexcept override {
    return &SPEC_LIMITS_TUNABLE_PARAMS_LAYOUT_HASH;
  }

protected:
/// Extra derived-class initialization after spec registration.
[[nodiscard]] virtual std::uint8_t onInit() noexcept { return 0; }
  /// Accept or reject an incoming parameter set (policy hook).
  [[nodiscard]] virtual bool validateParams(const SpecLimitsTunableParams&) noexcept { return true; }
  /// Called after every successful publish (seed state from params here).
  virtual void onParamsLoaded() noexcept {}
  /// Nudge the value; out-of-band results reject and count.
  [[nodiscard]] virtual std::uint8_t onNudge(const NudgeRequest& request) noexcept = 0;

  [[nodiscard]] std::uint8_t doInit() noexcept override {
    this->template registerTask<TDerived, &TDerived::step>(
        static_cast<std::uint8_t>(TaskUid::STEP), static_cast<TDerived*>(this), "step");
    this->registerData(system_core::data::DataCategory::TUNABLE_PARAM, "tunableParams",
                       &inspectParams_, sizeof(SpecLimitsTunableParams));
    this->registerData(system_core::data::DataCategory::STATE, "state", &state_.get(),
                       sizeof(SpecLimitsState));
    return onInit();
  }

  [[nodiscard]] std::uint8_t handleCommand(std::uint16_t opcode,
                                           apex::compat::rospan<std::uint8_t> payload,
                                           std::vector<std::uint8_t>& response) noexcept override {
    switch (opcode) {
    case 0x0238U: {
      if (payload.size() != sizeof(NudgeRequest)) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      NudgeRequest request{};
      std::memcpy(&request, payload.data(), sizeof(request));
      return onNudge(request);
    }
    default:
      return TBase::handleCommand(opcode, payload, response);
    }
  }

  system_core::system_component::ParamBank<SpecLimitsTunableParams> paramBank_{};
  SpecLimitsTunableParams inspectParams_{};
  system_core::data::State<SpecLimitsState> state_{};
};

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_LIMITS_SPEC_BASE_HPP
