# ==============================================================================
# TprmConstraintGen.cmake - assemble an app's constraint registry TU
#
# Runs at build time via cmake -P. Inputs:
#   -DROWS_MANIFEST=<file>   lines of "<fullUid>|<rows.json path>"
#   -DOUTPUT=<registry.cpp>
#
# Each rows file is the cfg2bin --constraint-rows output for one payload:
# a JSON array of {offset, size, kind, min?, max?, step?, allowed?}.
# The generated TU defines the strong apexTprmConstraintLookup the weak
# reference in TprmPayload.hpp resolves against, mapping each fullUid to
# its compiled-in table. Payloads with no constrained fields get no
# table (lookup returns null; the identity/integrity checks still run).
# ==============================================================================

# cmake-lint: disable=E1120
# The generated-TU string literal below carries C++ parentheses that
# cmakelang's parser misreads, surfacing phantom argument errors at the
# RANGE loops (the identical loop form passes lint in Coverage.cmake).

file(STRINGS "${ROWS_MANIFEST}" _pairs)

set(_body "")
set(_cases "")
set(_uid_index 0)

foreach (_pair IN LISTS _pairs)
  if (_pair STREQUAL "")
    continue()
  endif ()
  string(REGEX REPLACE "\\|.*$" "" _uid "${_pair}")
  string(REGEX REPLACE "^[^|]*\\|" "" _rows_file "${_pair}")

  if (NOT EXISTS "${_rows_file}")
    continue()
  endif ()
  file(READ "${_rows_file}" _rows_json)
  string(JSON _count LENGTH "${_rows_json}")
  if (_count EQUAL 0)
    continue()
  endif ()

  set(_entries "")
  math(EXPR _last "${_count} - 1")
  foreach (_i RANGE 0 ${_last})
    string(JSON _offset GET "${_rows_json}" ${_i} offset)
    string(JSON _size GET "${_rows_json}" ${_i} size)
    string(JSON _kind GET "${_rows_json}" ${_i} kind)

    foreach (_key min max step)
      string(
        JSON
        _${_key}
        ERROR_VARIABLE
        _${_key}_err
        GET
        "${_rows_json}"
        ${_i}
        ${_key}
      )
      if (_${_key}_err)
        set(_has_${_key} "false")
        set(_${_key} "0.0")
      else ()
        set(_has_${_key} "true")
      endif ()
    endforeach ()

    set(_allowed_ptr "nullptr")
    set(_allowed_count 0)
    string(
      JSON
      _allowed
      ERROR_VARIABLE
      _allowed_err
      GET
      "${_rows_json}"
      ${_i}
      allowed
    )
    if (NOT _allowed_err)
      string(JSON _allowed_count LENGTH "${_allowed}")
      set(_vals "")
      math(EXPR _alast "${_allowed_count} - 1")
      foreach (_a RANGE 0 ${_alast})
        string(JSON _v GET "${_allowed}" ${_a})
        string(APPEND _vals "${_v}, ")
      endforeach ()
      string(APPEND _body "const double kAllowed_${_uid_index}_${_i}[] = {${_vals}};\n")
      set(_allowed_ptr "kAllowed_${_uid_index}_${_i}")
    endif ()

    string(
      APPEND
      _entries
      "    {${_offset}, ${_size}, TprmFieldKind{${_kind}}, ${_has_min}, ${_has_max}, ${_has_step}, ${_min}, ${_max}, ${_step}, ${_allowed_ptr}, ${_allowed_count}},\n"
    )
  endforeach ()

  string(APPEND _body "const TprmConstraintEntry kEntries_${_uid_index}[] = {\n${_entries}};\n")
  string(APPEND _body
         "const TprmConstraintTable kTable_${_uid_index}{kEntries_${_uid_index}, ${_count}};\n\n"
  )
  string(APPEND _cases "  case ${_uid}U:\n    return &kTable_${_uid_index};\n")
  math(EXPR _uid_index "${_uid_index} + 1")
endforeach ()

set(_tu
    "// Generated by TprmConstraintGen.cmake from the packing manifest's
// constraint rows. The strong definition the weak reference in
// TprmPayload.hpp resolves against: fullUid -> compiled-in table.

#include \"src/system/core/infrastructure/system_component/posix/inc/TprmPayload.hpp\"

#include <cstdint>

namespace {

using system_core::system_component::TprmConstraintEntry;
using system_core::system_component::TprmConstraintTable;
using system_core::system_component::TprmFieldKind;

${_body}} // namespace

extern \"C\" const TprmConstraintTable* apexTprmConstraintLookup(std::uint32_t fullUid) noexcept {
  switch (fullUid) {
${_cases}  default:
    return nullptr;
  }
}
"
)

file(WRITE "${OUTPUT}" "${_tu}")
