/**
 * @file 00_HorizonProceduralAtm_dTest.cpp
 * @brief Integration test: load a horizon-CLI-generated .atm through Apex.
 *
 * Goals:
 *  - Verify the horizon procedural atmosphere pipeline emits an apex-readable
 *    .atm file (wire-format compatibility check, parallel to the gravity
 *    and terrain dtests).
 *  - Validate the AtmReader -> model construction path that runtime drag
 *    code will use.
 *
 * Prereqs:
 *  - data/procedural/alpha.atm generated by:
 *      horizon_world gen-atmosphere --spec tools/world_data/samples/alpha.toml \
 *          --out alpha.atm
 *    (alpha.toml's [atmosphere] section selects model_type = "exponential")
 *
 * Notes:
 *  - SKIPs cleanly if the fixture is absent.
 *  - Run manually:
 *      ./build/native-linux-debug/bin/devtests/SimEnvironmentAtmosphere_Dev \
 *          --gtest_filter="HorizonProceduralAtm*"
 */

#include "src/sim/environment/atmosphere/inc/Atm.hpp"
#include "src/sim/environment/atmosphere/inc/ExponentialAtmosphere.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <cstdint>
#include <iostream>

using sim::environment::atmosphere::AtmModelType;
using sim::environment::atmosphere::AtmosphereState;
using sim::environment::atmosphere::AtmReader;
using sim::environment::atmosphere::AtmRecord;
using sim::environment::atmosphere::ExponentialAtmosphere;
using sim::environment::atmosphere::isSuccess;

namespace {

constexpr const char* K_ALPHA_ATM_PATH = "src/sim/environment/atmosphere/data/procedural/alpha.atm";

} // namespace

TEST(HorizonProceduralAtm, FileLoadsAndHeaderMatchesAlphaSpec) {
  AtmReader r;
  if (!r.open(K_ALPHA_ATM_PATH)) {
    GTEST_SKIP() << "procedural fixture not present: " << K_ALPHA_ATM_PATH
                 << "  (generate via horizon_world gen-atmosphere --spec alpha.toml)";
  }

  std::cout << "\n=== Horizon procedural .atm: load + header ===\n";
  std::cout << "  body         : " << std::string(r.header().body, 16).c_str() << "\n";
  std::cout << "  model_type   : " << static_cast<unsigned>(r.header().model_type) << "\n";
  std::cout << "  n_records    : " << r.header().n_records << "\n";
  std::cout << "  R_specific   : " << r.header().R_specific << " J/(kg*K)\n";
  std::cout << "  gamma        : " << r.header().gamma << "\n";

  // alpha.toml [atmosphere] selects model_type = "exponential" with
  // CO2 thermo (R_specific = 192.0, gamma = 1.31).
  EXPECT_EQ(r.header().model_type, static_cast<std::uint8_t>(AtmModelType::kExponential));
  EXPECT_EQ(r.header().n_records, 1u);
  EXPECT_DOUBLE_EQ(r.header().R_specific, 192.0);
  EXPECT_DOUBLE_EQ(r.header().gamma, 1.31);
}

TEST(HorizonProceduralAtm, RecordPopulatesExponentialModel) {
  AtmReader r;
  if (!r.open(K_ALPHA_ATM_PATH)) {
    GTEST_SKIP() << "procedural fixture not present";
  }
  AtmRecord rec{};
  ASSERT_TRUE(r.readAllRecords(&rec, 1));

  // Build an ExponentialAtmosphere from the .atm record (rho0, T0, H).
  ExponentialAtmosphere exp;
  ASSERT_TRUE(isSuccess(exp.init(/*rho0=*/rec.f0, /*T0=*/rec.f1, /*scaleHeightM=*/rec.f2,
                                 /*gamma=*/r.header().gamma,
                                 /*R_specific=*/r.header().R_specific)));

  // Sanity check at the surface: rho = rho0.
  AtmosphereState s;
  ASSERT_TRUE(isSuccess(exp.query(0.0, 0.0, 0.0, s)));
  EXPECT_NEAR(s.rho, rec.f0, 1e-9);
  EXPECT_NEAR(s.T, rec.f1, 1e-9);

  // One scale height up: rho should drop by exactly e.
  AtmosphereState s_high;
  ASSERT_TRUE(isSuccess(exp.query(rec.f2, 0.0, 0.0, s_high)));
  EXPECT_NEAR(s.rho / s_high.rho, M_E, 1e-9);

  // Speed of sound from gamma * R * T.
  const double EXPECTED_A = std::sqrt(r.header().gamma * r.header().R_specific * rec.f1);
  EXPECT_NEAR(s.a, EXPECTED_A, 1e-6);

  std::cout << "\n=== Horizon procedural .atm: ExponentialAtmosphere query ===\n";
  std::cout << "  surface  rho=" << s.rho << "  T=" << s.T << "  a=" << s.a << "\n";
  std::cout << "  +1 H     rho=" << s_high.rho << " (expected " << s.rho / M_E << ")\n";
}
