/**
 * @file 01_HorizonRealUssa76_dTest.cpp
 * @brief Ground-truth integration test: convert canonical USSA76 (NASA
 *        TM-X-74335) through horizon's CLI -> .atm, load via apex's
 *        LayeredAtmosphere, verify state at well-known reference altitudes.
 *
 * Why this matters:
 *   The terrain dtests validate the Earth (SRTM) and Moon (LOLA) data paths
 *   against ground-truth landmarks. This is the atmosphere equivalent: the
 *   entire USSA76 path (paper -> convert-ussa76 -> .atm -> AtmReader ->
 *   LayeredAtmosphere -> query()) is validated against the published
 *   reference table.
 *
 * Tolerance reasoning:
 *   - At layer-base altitudes (0, 11, 20, 32, 47, 51, 71 km), our
 *     hydrostatic prediction equals the layer-table value exactly within
 *     double precision.
 *   - At interior altitudes within a non-isothermal layer, our model
 *     uses the altitude argument as GEOPOTENTIAL height (matching the
 *     USSA76 hydrostatic formula). Published reference tables typically
 *     index by GEOMETRIC height; the discrepancy is ~2% at 30 km and
 *     scales with altitude. We assert against the geopotential-correct
 *     prediction here.
 *
 * Prereqs:
 *   - data/earth/usa76.atm generated by:
 *       horizon_world convert-ussa76 --out usa76.atm
 *
 * Notes:
 *   - SKIPs cleanly if the fixture is absent.
 *   - Run manually:
 *       ./build/native-linux-debug/bin/devtests/SimEnvironmentAtmosphere_Dev \
 *           --gtest_filter="HorizonRealUssa76*"
 */

#include "src/sim/environment/atmosphere/inc/Atm.hpp"
#include "src/sim/environment/atmosphere/inc/LayeredAtmosphere.hpp"
#include "src/sim/environment/atmosphere/inc/earth/Ussa76Constants.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <cstdint>
#include <iomanip>
#include <iostream>

using sim::environment::atmosphere::AtmModelType;
using sim::environment::atmosphere::AtmosphereState;
using sim::environment::atmosphere::isSuccess;
using sim::environment::atmosphere::LayeredAtmosphere;

namespace {

constexpr const char* K_USSA76_ATM_PATH = "src/sim/environment/atmosphere/data/earth/usa76.atm";

} // namespace

/* ----------------------------- Tests ----------------------------- */

TEST(HorizonRealUssa76, FileLoadsAndHeaderHasExpectedShape) {
  LayeredAtmosphere atm;
  if (!isSuccess(atm.load(K_USSA76_ATM_PATH))) {
    GTEST_SKIP() << "USSA76 fixture not present: " << K_USSA76_ATM_PATH
                 << "  (generate via horizon_world convert-ussa76)";
  }
  EXPECT_EQ(atm.numLayers(), 7u);
  EXPECT_DOUBLE_EQ(atm.gasConstant(), sim::environment::atmosphere::earth::R_SPECIFIC);
  EXPECT_DOUBLE_EQ(atm.gamma(), sim::environment::atmosphere::earth::GAMMA);
  EXPECT_DOUBLE_EQ(atm.surfaceGravity(), sim::environment::atmosphere::earth::G0);
  // Layer base altitudes match the canonical USSA76 boundaries.
  EXPECT_DOUBLE_EQ(atm.layer(0).base_alt_m, 0.0);
  EXPECT_DOUBLE_EQ(atm.layer(1).base_alt_m, 11000.0);
  EXPECT_DOUBLE_EQ(atm.layer(6).base_alt_m, 71000.0);
}

TEST(HorizonRealUssa76, SeaLevelMatchesPublishedReference) {
  LayeredAtmosphere atm;
  if (!isSuccess(atm.load(K_USSA76_ATM_PATH))) {
    GTEST_SKIP() << "USSA76 fixture not present";
  }
  AtmosphereState s;
  ASSERT_TRUE(isSuccess(atm.query(0.0, 0.0, 0.0, s)));
  // USSA76 reference @ 0 m: T=288.15 K, P=101325 Pa, rho=1.225 kg/m^3,
  // a=340.294 m/s.
  EXPECT_NEAR(s.T, 288.15, 0.01);
  EXPECT_NEAR(s.P, 101325.0, 1.0);
  EXPECT_NEAR(s.rho, 1.225, 0.001);
  EXPECT_NEAR(s.a, 340.294, 0.01);
}

TEST(HorizonRealUssa76, LayerBasesMatchExactly) {
  // At every layer-base altitude, our model returns exactly T_b and P_b
  // from the table -- no integration error.
  LayeredAtmosphere atm;
  if (!isSuccess(atm.load(K_USSA76_ATM_PATH))) {
    GTEST_SKIP() << "USSA76 fixture not present";
  }

  struct Reference {
    const char* label;
    double alt_m;
    double T_K;
    double P_Pa;
  };
  const Reference REFS[] = {
      {"sea level", 0.0, 288.15, 101325.0},
      {"tropopause base", 11000.0, 216.65, 22632.06},
      {"stratosphere lower base", 20000.0, 216.65, 5474.889},
      {"stratosphere upper base", 32000.0, 228.65, 868.0187},
      {"stratopause base", 47000.0, 270.65, 110.9063},
      {"mesosphere lower base", 51000.0, 270.65, 66.93887},
      {"mesosphere upper base", 71000.0, 214.65, 3.95642},
  };

  std::cout << "\n=== USSA76 ground truth: layer-base altitudes ===\n";
  std::cout << std::fixed << std::setprecision(4);
  for (const auto& ref : REFS) {
    AtmosphereState s;
    ASSERT_TRUE(isSuccess(atm.query(ref.alt_m, 0.0, 0.0, s))) << ref.label;
    std::cout << "  " << std::setw(28) << std::left << ref.label << "  alt=" << std::setw(6)
              << ref.alt_m << "  T=" << s.T << "  P=" << s.P << "  rho=" << s.rho << "\n";
    EXPECT_NEAR(s.T, ref.T_K, 0.01) << ref.label << " temperature";
    EXPECT_NEAR(s.P, ref.P_Pa, std::max(0.5, ref.P_Pa * 1e-4)) << ref.label << " pressure";
  }
}

TEST(HorizonRealUssa76, InteriorTroposphereInterpolation) {
  // 5 km is well inside the troposphere (lapse = -0.0065 K/m).
  // T(5000) = 288.15 + (-0.0065)*5000 = 255.65 K
  // P(5000) = 101325 * (288.15 / 255.65)^(9.80665/(287.058 * -0.0065))
  //         ~ 54019 Pa  (matches USSA76 table @ 5 km geopotential)
  LayeredAtmosphere atm;
  if (!isSuccess(atm.load(K_USSA76_ATM_PATH))) {
    GTEST_SKIP() << "USSA76 fixture not present";
  }
  AtmosphereState s;
  ASSERT_TRUE(isSuccess(atm.query(5000.0, 0.0, 0.0, s)));
  EXPECT_NEAR(s.T, 255.65, 0.01);
  EXPECT_NEAR(s.P, 54019.9, 100.0);
  // rho = P/(R*T) per ideal gas law.
  EXPECT_NEAR(s.rho, s.P / (atm.gasConstant() * s.T), 1e-9);
}

TEST(HorizonRealUssa76, MesosphereDensityIsLow) {
  // Sanity: at 71 km (top mesosphere base), density should be many orders
  // of magnitude below sea-level.
  LayeredAtmosphere atm;
  if (!isSuccess(atm.load(K_USSA76_ATM_PATH))) {
    GTEST_SKIP() << "USSA76 fixture not present";
  }
  AtmosphereState s_top;
  ASSERT_TRUE(isSuccess(atm.query(71000.0, 0.0, 0.0, s_top)));
  EXPECT_LT(s_top.rho, 1e-3);
  EXPECT_GT(s_top.rho, 1e-6);
  // Speed of sound at 71 km: a = sqrt(gamma * R * T) ~ 294 m/s for T=214.65.
  EXPECT_NEAR(s_top.a, std::sqrt(1.4 * 287.058 * 214.65), 0.01);
}

TEST(HorizonRealUssa76, AltitudeAboveTableRejected) {
  LayeredAtmosphere atm;
  if (!isSuccess(atm.load(K_USSA76_ATM_PATH))) {
    GTEST_SKIP() << "USSA76 fixture not present";
  }
  // 120 km is well above the documented top + extrapolation tolerance.
  AtmosphereState s;
  EXPECT_EQ(atm.query(120000.0, 0.0, 0.0, s),
            sim::environment::atmosphere::Status::WARN_OUT_OF_VALID_RANGE);
}
