// Generated by cdef_gen from the SpecSensor spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_RECALIBRATE_REQUEST_HPP
#define APEX_CDEF_AUTO_RECALIBRATE_REQUEST_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (4 bytes, packed by
/// construction: field order and sizes come from the spec).
struct RecalibrateRequest {
  float referenceValue{}; ///< New calibrated reference.
};
static_assert(sizeof(RecalibrateRequest) == 4, "layout diverged from the spec");
static_assert(offsetof(RecalibrateRequest, referenceValue) == 0, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t RECALIBRATE_REQUEST_LAYOUT_HASH = 0x4BABF3B0U;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_RECALIBRATE_REQUEST_HPP
