// Generated by cdef_gen from the SpecSensor spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SET_MODE_REQUEST_HPP
#define APEX_CDEF_AUTO_SET_MODE_REQUEST_HPP

#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (1 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SetModeRequest {
  std::uint8_t mode{}; ///< Requested mode (0=IDLE, 1=MEASURE, 2=FAULT_INJECT).
};
static_assert(sizeof(SetModeRequest) == 1, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SET_MODE_REQUEST_LAYOUT_HASH = 0xD9AF370AU;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SET_MODE_REQUEST_HPP
