// Generated by cdef_gen from the SpecSensor spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_SENSOR_STATE_HPP
#define APEX_CDEF_AUTO_SPEC_SENSOR_STATE_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (20 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecSensorState {
  float elapsed{}; ///< Seconds since boot or last recalibration.
  float drift{}; ///< Accumulated drift away from the reference.
  std::uint32_t samples{}; ///< Measurements taken since boot or reset.
  std::uint32_t rejects{}; ///< Commands rejected (bad mode transitions).
  std::uint8_t mode{}; ///< Active mode (0=IDLE, 1=MEASURE, 2=FAULT_INJECT).
  std::uint8_t reserved[3]{}; ///< Alignment padding.
};
static_assert(sizeof(SpecSensorState) == 20, "layout diverged from the spec");
static_assert(offsetof(SpecSensorState, elapsed) == 0, "field offset diverged");
static_assert(offsetof(SpecSensorState, drift) == 4, "field offset diverged");
static_assert(offsetof(SpecSensorState, samples) == 8, "field offset diverged");
static_assert(offsetof(SpecSensorState, rejects) == 12, "field offset diverged");
static_assert(offsetof(SpecSensorState, mode) == 16, "field offset diverged");
static_assert(offsetof(SpecSensorState, reserved) == 17, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_SENSOR_STATE_LAYOUT_HASH = 0x3B5D3A65U;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_SENSOR_STATE_HPP
