// Generated by cdef_gen from the SpecSensor spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Implement the on<Command> hooks in the component (stub-generated).
#ifndef APEX_CDEF_AUTO_SPEC_SENSOR_CMD_BASE_HPP
#define APEX_CDEF_AUTO_SPEC_SENSOR_CMD_BASE_HPP

#include "src/system/core/infrastructure/system_component/base/inc/SystemComponentStatus.hpp"
#include "src/utilities/compatibility/inc/compat_span.hpp"
#include "SetModeRequest_auto.hpp"
#include "RecalibrateRequest_auto.hpp"
#include "StatsResponse_auto.hpp"

#include <cstdint>
#include <cstring>
#include <vector>

namespace appsim {
namespace spec {

/// Spec-generated command dispatch: size-verified decode, hook
/// invocation, response encode. Unknown opcodes fall through to
/// the tier base.
template <typename TBase> class SpecSensorCmdBase : public TBase {
public:
using TBase::TBase;

protected:
  /// Select the operating mode; FAULT_INJECT only from MEASURE.
  [[nodiscard]] virtual std::uint8_t onSetMode(const SetModeRequest& request) noexcept = 0;
  /// Set a new reference, zero the drift, return the stats snapshot.
  [[nodiscard]] virtual std::uint8_t onRecalibrate(const RecalibrateRequest& request, StatsResponse& response) noexcept = 0;
  /// Return the stats snapshot.
  [[nodiscard]] virtual std::uint8_t onGetStats(StatsResponse& response) noexcept = 0;
  /// Zero counters and drift; mode returns to the tunable default.
  [[nodiscard]] virtual std::uint8_t onReset() noexcept = 0;

[[nodiscard]] std::uint8_t handleCommand(std::uint16_t opcode,
apex::compat::rospan<std::uint8_t> payload,
std::vector<std::uint8_t>& response) noexcept override {
switch (opcode) {
    case 0x0200U: {
      if (payload.size() != sizeof(SetModeRequest)) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      SetModeRequest request{};
      std::memcpy(&request, payload.data(), sizeof(request));
      return onSetMode(request);
    }
    case 0x0201U: {
      if (payload.size() != sizeof(RecalibrateRequest)) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      RecalibrateRequest request{};
      std::memcpy(&request, payload.data(), sizeof(request));
      StatsResponse reply{};
      const std::uint8_t RC = onRecalibrate(request, reply);
      response.resize(sizeof(reply));
      std::memcpy(response.data(), &reply, sizeof(reply));
      return RC;
    }
    case 0x0202U: {
      if (!payload.empty()) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      StatsResponse reply{};
      const std::uint8_t RC = onGetStats(reply);
      response.resize(sizeof(reply));
      std::memcpy(response.data(), &reply, sizeof(reply));
      return RC;
    }
    case 0x0203U: {
      if (!payload.empty()) {
        return static_cast<std::uint8_t>(system_core::system_component::Status::ERROR_PARAM);
      }
      return onReset();
    }
    default:
return TBase::handleCommand(opcode, payload, response);
}
}
};

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_SENSOR_CMD_BASE_HPP
