// Generated by cdef_gen from the SpecSensor spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_SPEC_SENSOR_TUNABLE_PARAMS_HPP
#define APEX_CDEF_AUTO_SPEC_SENSOR_TUNABLE_PARAMS_HPP

#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (20 bytes, packed by
/// construction: field order and sizes come from the spec).
struct SpecSensorTunableParams {
  float sampleRateHz{10.0F}; ///< Model sample rate [Hz], range 1..100.
  float referenceValue{25.0F}; ///< Calibrated reference the measurement drifts around.
  float driftRate{0.05F}; ///< Drift per second away from reference, range 0..5.
  float noiseAmplitude{0.1F}; ///< Peak noise amplitude, >= 0.
  std::uint8_t mode{0}; ///< Startup mode (0=IDLE, 1=MEASURE, 2=FAULT_INJECT).
  std::uint8_t reserved[3]{}; ///< Alignment padding.
};
static_assert(sizeof(SpecSensorTunableParams) == 20, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t SPEC_SENSOR_TUNABLE_PARAMS_LAYOUT_HASH = 0x2924797DU;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_SPEC_SENSOR_TUNABLE_PARAMS_HPP
