// Generated by cdef_gen from the SpecSensor spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_STATS_RESPONSE_HPP
#define APEX_CDEF_AUTO_STATS_RESPONSE_HPP

#include <cstddef>
#include <cstdint>

namespace appsim {
namespace spec {

/// Spec-defined tunable parameters (16 bytes, packed by
/// construction: field order and sizes come from the spec).
struct StatsResponse {
  std::uint32_t samples{}; ///< Measurements taken since boot or reset.
  std::uint32_t rejects{}; ///< Commands rejected.
  float lastValue{}; ///< Most recent measurement.
  std::uint8_t mode{}; ///< Active mode.
  std::uint8_t reserved[3]{}; ///< Alignment padding.
};
static_assert(sizeof(StatsResponse) == 16, "layout diverged from the spec");
static_assert(offsetof(StatsResponse, samples) == 0, "field offset diverged");
static_assert(offsetof(StatsResponse, rejects) == 4, "field offset diverged");
static_assert(offsetof(StatsResponse, lastValue) == 8, "field offset diverged");
static_assert(offsetof(StatsResponse, mode) == 12, "field offset diverged");
static_assert(offsetof(StatsResponse, reserved) == 13, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t STATS_RESPONSE_LAYOUT_HASH = 0xD39B482BU;

} // namespace spec
} // namespace appsim
#endif // APEX_CDEF_AUTO_STATS_RESPONSE_HPP
