// Generated by cdef_gen from the ActionComponent spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_STANDALONE_WAIT_CONDITION_TPRM_HPP
#define APEX_CDEF_AUTO_STANDALONE_WAIT_CONDITION_TPRM_HPP

#include <cstddef>
#include <cstdint>

namespace system_core {
namespace action {

/// Spec-defined tunable parameters (20 bytes, packed by
/// construction: field order and sizes come from the spec).
struct __attribute__((packed)) StandaloneWaitConditionTprm {
  std::uint32_t targetFullUid{0}; ///< Component fullUid to watch.
  std::uint8_t targetCategory{0}; ///< DataCategory enum value.
  std::uint16_t targetByteOffset{0}; ///< Byte offset into the data block.
  std::uint8_t targetByteLen{0}; ///< Byte length to compare.
  std::uint8_t predicate{0}; ///< WatchPredicate enum value.
  std::uint8_t dataType{0}; ///< WatchDataType enum value.
  std::uint8_t threshold[8]{}; ///< Raw threshold bytes.
  std::uint8_t enabled{0}; ///< 1 = condition active.
  std::uint8_t reserved{0}; ///< Explicit padding.
};
static_assert(sizeof(StandaloneWaitConditionTprm) == 20, "layout diverged from the spec");
static_assert(offsetof(StandaloneWaitConditionTprm, targetFullUid) == 0, "field offset diverged");
static_assert(offsetof(StandaloneWaitConditionTprm, targetCategory) == 4, "field offset diverged");
static_assert(offsetof(StandaloneWaitConditionTprm, targetByteOffset) == 5, "field offset diverged");
static_assert(offsetof(StandaloneWaitConditionTprm, targetByteLen) == 7, "field offset diverged");
static_assert(offsetof(StandaloneWaitConditionTprm, predicate) == 8, "field offset diverged");
static_assert(offsetof(StandaloneWaitConditionTprm, dataType) == 9, "field offset diverged");
static_assert(offsetof(StandaloneWaitConditionTprm, threshold) == 10, "field offset diverged");
static_assert(offsetof(StandaloneWaitConditionTprm, enabled) == 18, "field offset diverged");
static_assert(offsetof(StandaloneWaitConditionTprm, reserved) == 19, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t STANDALONE_WAIT_CONDITION_TPRM_LAYOUT_HASH = 0x84C98ADBU;

} // namespace action
} // namespace system_core
#endif // APEX_CDEF_AUTO_STANDALONE_WAIT_CONDITION_TPRM_HPP
