// Generated by cdef_gen from the ActionComponent spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_STANDALONE_SEQUENCE_TPRM_HPP
#define APEX_CDEF_AUTO_STANDALONE_SEQUENCE_TPRM_HPP

#include <cstddef>
#include <cstdint>

#include "StandaloneStepTprm_auto.hpp"

namespace system_core {
namespace action {

/// Spec-defined tunable parameters (1032 bytes, packed by
/// construction: field order and sizes come from the spec).
struct __attribute__((packed)) StandaloneSequenceTprm {
  std::uint16_t sequenceId{0}; ///< Unique ID for logging/telemetry.
  std::uint16_t eventId{0}; ///< Trigger event (0 = manual start only).
  std::uint8_t stepCount{0}; ///< Number of valid steps (0-16).
  std::uint8_t repeatCount{0}; ///< Repeat count (0 = once, 0xFF = forever).
  std::uint8_t type{0}; ///< SequenceType enum (0=RTS, 1=ATS).
  std::uint8_t armed{0}; ///< 1 = armed on load.
  StandaloneStepTprm steps[16]{}; ///< Step table (SEQUENCE_MAX_STEPS).
};
static_assert(sizeof(StandaloneSequenceTprm) == 1032, "layout diverged from the spec");
static_assert(offsetof(StandaloneSequenceTprm, sequenceId) == 0, "field offset diverged");
static_assert(offsetof(StandaloneSequenceTprm, eventId) == 2, "field offset diverged");
static_assert(offsetof(StandaloneSequenceTprm, stepCount) == 4, "field offset diverged");
static_assert(offsetof(StandaloneSequenceTprm, repeatCount) == 5, "field offset diverged");
static_assert(offsetof(StandaloneSequenceTprm, type) == 6, "field offset diverged");
static_assert(offsetof(StandaloneSequenceTprm, armed) == 7, "field offset diverged");
static_assert(offsetof(StandaloneSequenceTprm, steps) == 8, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t STANDALONE_SEQUENCE_TPRM_LAYOUT_HASH = 0xF443AD7BU;

} // namespace action
} // namespace system_core
#endif // APEX_CDEF_AUTO_STANDALONE_SEQUENCE_TPRM_HPP
