// Generated by cdef_gen from the ActionComponent spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_STANDALONE_STEP_TPRM_HPP
#define APEX_CDEF_AUTO_STANDALONE_STEP_TPRM_HPP

#include <cstddef>
#include <cstdint>

#include "StandaloneWaitConditionTprm_auto.hpp"

namespace system_core {
namespace action {

/// Spec-defined tunable parameters (64 bytes, packed by
/// construction: field order and sizes come from the spec).
struct __attribute__((packed)) StandaloneStepTprm {
  std::uint32_t targetFullUid{0}; ///< Target component.
  std::uint8_t targetCategory{0}; ///< DataCategory enum value.
  std::uint16_t targetByteOffset{0}; ///< Byte offset.
  std::uint8_t targetByteLen{0}; ///< Byte length.
  std::uint8_t actionType{0}; ///< ActionType enum (COMMAND=0, ARM_CONTROL=1).
  std::uint8_t armTarget{0}; ///< ArmControlTarget enum.
  std::uint8_t armIndex{0}; ///< Table index.
  std::uint8_t armState{0}; ///< 1 = arm, 0 = disarm.
  std::uint16_t commandOpcode{0}; ///< Command opcode.
  std::uint8_t commandPayloadLen{0}; ///< Payload length.
  std::uint8_t commandPayload[16]{}; ///< Command payload bytes.
  std::uint32_t delayCycles{0}; ///< Delay (RTS: relative, ATS: absolute offset).
  std::uint32_t timeoutCycles{0}; ///< Max wait (0 = no timeout).
  std::uint8_t onTimeout{0}; ///< StepTimeoutPolicy enum.
  std::uint8_t onComplete{0}; ///< StepCompletionAction enum.
  std::uint8_t gotoStep{0}; ///< Target for GOTO_STEP or START_RTS slot.
  std::uint8_t retryMax{0}; ///< Max retries on timeout.
  StandaloneWaitConditionTprm waitCondition{}; ///< Optional hold condition.
  std::uint8_t reserved{0}; ///< Explicit padding.
};
static_assert(sizeof(StandaloneStepTprm) == 64, "layout diverged from the spec");
static_assert(offsetof(StandaloneStepTprm, targetFullUid) == 0, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, targetCategory) == 4, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, targetByteOffset) == 5, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, targetByteLen) == 7, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, actionType) == 8, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, armTarget) == 9, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, armIndex) == 10, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, armState) == 11, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, commandOpcode) == 12, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, commandPayloadLen) == 14, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, commandPayload) == 15, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, delayCycles) == 31, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, timeoutCycles) == 35, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, onTimeout) == 39, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, onComplete) == 40, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, gotoStep) == 41, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, retryMax) == 42, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, waitCondition) == 43, "field offset diverged");
static_assert(offsetof(StandaloneStepTprm, reserved) == 63, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t STANDALONE_STEP_TPRM_LAYOUT_HASH = 0x9F83068FU;

} // namespace action
} // namespace system_core
#endif // APEX_CDEF_AUTO_STANDALONE_STEP_TPRM_HPP
