// Generated by cdef_gen from the TelemetryManager spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_TELEMETRY_MANAGER_TPRM_HPP
#define APEX_CDEF_AUTO_TELEMETRY_MANAGER_TPRM_HPP

#include <cstddef>
#include <cstdint>

#include "TelemetrySubscription_auto.hpp"

namespace system_core {
namespace support {

/// Spec-defined tunable parameters (520 bytes, packed by
/// construction: field order and sizes come from the spec).
struct TelemetryManagerTprm {
  std::uint16_t collectRateHz{1}; ///< Base collect task rate (Hz); subscriptions divide from this.
  std::uint16_t reserved0{0}; ///< Explicit padding.
  std::uint32_t reserved1{0}; ///< Explicit padding.
  TelemetrySubscription subscriptions[32]{}; ///< Push channel table; unused entries have active = 0.
};
static_assert(sizeof(TelemetryManagerTprm) == 520, "layout diverged from the spec");
static_assert(offsetof(TelemetryManagerTprm, collectRateHz) == 0, "field offset diverged");
static_assert(offsetof(TelemetryManagerTprm, reserved0) == 2, "field offset diverged");
static_assert(offsetof(TelemetryManagerTprm, reserved1) == 4, "field offset diverged");
static_assert(offsetof(TelemetryManagerTprm, subscriptions) == 8, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t TELEMETRY_MANAGER_TPRM_LAYOUT_HASH = 0x816D61C8U;

} // namespace support
} // namespace system_core
#endif // APEX_CDEF_AUTO_TELEMETRY_MANAGER_TPRM_HPP
