// Generated by cdef_gen from the TelemetryManager spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_TELEMETRY_SUBSCRIPTION_HPP
#define APEX_CDEF_AUTO_TELEMETRY_SUBSCRIPTION_HPP

#include <cstddef>
#include <cstdint>

namespace system_core {
namespace support {

/// Spec-defined tunable parameters (16 bytes, packed by
/// construction: field order and sizes come from the spec).
struct TelemetrySubscription {
  std::uint32_t fullUid{0}; ///< Target component fullUid (e.g. 0x00D000).
  std::uint8_t category{0}; ///< DataCategory enum (0=STATIC, 1=TUNABLE, 2=STATE, 3=INPUT, 4=OUTPUT).
  std::uint8_t active{0}; ///< 1 = active, 0 = inactive.
  std::uint16_t opcode{0}; ///< APROTO opcode for the outbound telemetry packet.
  std::uint16_t offset{0}; ///< Byte offset into the data block (0 = start).
  std::uint16_t length{0}; ///< Bytes to read (0 = entire block).
  std::uint16_t rateDiv{1}; ///< Rate divisor: push every N collect ticks (1 = every tick).
  std::uint16_t reserved{0}; ///< Explicit padding.
};
static_assert(sizeof(TelemetrySubscription) == 16, "layout diverged from the spec");
static_assert(offsetof(TelemetrySubscription, fullUid) == 0, "field offset diverged");
static_assert(offsetof(TelemetrySubscription, category) == 4, "field offset diverged");
static_assert(offsetof(TelemetrySubscription, active) == 5, "field offset diverged");
static_assert(offsetof(TelemetrySubscription, opcode) == 6, "field offset diverged");
static_assert(offsetof(TelemetrySubscription, offset) == 8, "field offset diverged");
static_assert(offsetof(TelemetrySubscription, length) == 10, "field offset diverged");
static_assert(offsetof(TelemetrySubscription, rateDiv) == 12, "field offset diverged");
static_assert(offsetof(TelemetrySubscription, reserved) == 14, "field offset diverged");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t TELEMETRY_SUBSCRIPTION_LAYOUT_HASH = 0x66BDFF8AU;

} // namespace support
} // namespace system_core
#endif // APEX_CDEF_AUTO_TELEMETRY_SUBSCRIPTION_HPP
