// Generated by cdef_gen from the TelemetryManager spec -- DO NOT EDIT.
// Regenerate: make cdef (check-cdef diffs this file against the spec).
// Overrides belong in the component's .ovr/ directory.
#ifndef APEX_CDEF_AUTO_TELEMETRY_MANAGER_STATE_HPP
#define APEX_CDEF_AUTO_TELEMETRY_MANAGER_STATE_HPP

#include <cstdint>

namespace system_core {
namespace support {

/// Spec-defined tunable parameters (16 bytes, packed by
/// construction: field order and sizes come from the spec).
struct TelemetryManagerState {
  std::uint32_t collectCount{0};
  std::uint32_t packetsSent{0}; ///< Total telemetry packets pushed to bus.
  std::uint32_t sendFailures{0}; ///< Failed pushes (queue full or registry miss).
  std::uint16_t activeCount{0}; ///< Number of active subscriptions.
  std::uint16_t reserved{0}; ///< Alignment padding.
};
static_assert(sizeof(TelemetryManagerState) == 16, "layout diverged from the spec");

/// Layout hash the v3 payload prelude must carry for this struct
/// (canonical field-spec CRC-32; stamped by cfg2bin from the same
/// spec-generated template).
inline constexpr std::uint32_t TELEMETRY_MANAGER_STATE_LAYOUT_HASH = 0x307F7315U;

} // namespace support
} // namespace system_core
#endif // APEX_CDEF_AUTO_TELEMETRY_MANAGER_STATE_HPP
