//! Tunable Parameters: parse a C++ header and emit a JSON/TOML template.
//!
//! The output is intended as a **starting point only**. It preserves field
//! declaration order and includes size/dim information where possible, but it
//! is not a full C++ parser. Users should review and adjust as needed.

use std::{
    fmt,
    path::{Path, PathBuf},
    str::FromStr,
};

// JSON metadata representation produced by the parser.
use serde_json::Value as Metadata;

/// Output format selector.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Format {
    Json,
    Toml,
}

impl FromStr for Format {
    type Err = Error;
    #[inline]
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        if s.eq_ignore_ascii_case("json") {
            Ok(Format::Json)
        } else if s.eq_ignore_ascii_case("toml") {
            Ok(Format::Toml)
        } else {
            Err(Error::InvalidFormat(s.to_string()))
        }
    }
}

impl fmt::Display for Format {
    #[inline]
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Format::Json => "json",
            Format::Toml => "toml",
        })
    }
}

/// Generation options (minimal; can be extended later).
#[derive(Debug, Clone, Default)]
pub struct TemplateOptions {
    /// If true, fail on ambiguous constructs instead of emitting placeholders.
    pub strict: bool,
    /// If set, only emit the named struct (filter out others).
    pub struct_filter: Option<String>,
}

/// Unified error type for this module.
#[derive(Debug)]
pub enum Error {
    Io(std::io::Error),
    InvalidHeaderSuffix(PathBuf),
    InvalidFormat(String),
    Parse(String),
    Emit(String),
    InvalidArgs(String),
}

impl std::error::Error for Error {}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Error::Io(e) => write!(f, "I/O error: {e}"),
            Error::InvalidHeaderSuffix(p) => {
                write!(f, "invalid header suffix for: {}", p.display())
            }
            Error::InvalidFormat(s) => write!(f, "invalid format: {s}"),
            Error::Parse(s) => write!(f, "parse error: {s}"),
            Error::Emit(s) => write!(f, "emit error: {s}"),
            Error::InvalidArgs(s) => write!(f, "invalid arguments: {s}"),
        }
    }
}

impl From<std::io::Error> for Error {
    #[inline]
    fn from(e: std::io::Error) -> Self {
        Error::Io(e)
    }
}

/// Orchestrates: read header → build metadata → write file (or return path).
///
/// If `output_path` is `None`, the path is inferred by replacing `.hpp|.h` with
/// `.json` or `.toml` based on `format`.
pub fn generate_template(
    header_path: &Path,
    format: Format,
    output_path: Option<&Path>,
    opts: &TemplateOptions,
) -> Result<PathBuf, Error> {
    // 1) Read the header
    let content = parser::read_file(header_path)?;

    // 2) Parse to metadata (serde_json::Value map)
    let metadata: Metadata = parser::parse_header(&content, opts)?;

    // 3) Decide output path (explicit or inferred)
    let out_path: PathBuf = match output_path {
        Some(p) => PathBuf::from(p),
        None => path::infer_output_path_impl(header_path, format)?,
    };

    // 4) Emit in the requested format
    match format {
        Format::Json => emit::write_json(&metadata, &out_path)?,
        Format::Toml => emit::write_toml(&metadata, &out_path)?,
    }

    Ok(out_path)
}

/// Derive an output path from a header path and a target format.
///
/// Replaces `.hpp|.h` with `.json` or `.toml`. Returns `InvalidHeaderSuffix` if
/// the input doesn't end with one of the allowed suffixes.
#[inline]
pub fn infer_output_path(header_path: &Path, format: Format) -> Result<PathBuf, Error> {
    path::infer_output_path_impl(header_path, format)
}

// === Internals ===
pub mod binary;
mod emit;
pub mod manifest;
pub mod pack;
mod parser;
mod path;

// Re-export parser functions for apex_data_gen
pub use parser::{collect_enums, parse_header, read_file, ParsedEnum};

/// Banner included at the top of all generated metadata.
pub(crate) const AUTOGEN_NOTE: &str = "This file is autogenerated. Do not modify manually!";
